"use client";

import { api } from "@/lib/api";
import { hasStoredRolePermission } from "@/lib/rolePermissions";
import { FormEvent, useCallback, useEffect, useState } from "react";

type Notification = { id: string; channel: string; event_type: string; recipient: string; subject?: string; body: string; status: string; error?: string; created_at: string };
const field = "h-10 w-full rounded-md border border-line px-3 text-sm";
export default function TransportNotificationsPage() {
  const [rows, setRows] = useState<Notification[]>([]); const [message, setMessage] = useState(""); const canWrite = hasStoredRolePermission("transport", "write");
  const load = useCallback(async () => setRows(await api<Notification[]>("/api/v1/transport/notifications")), []); useEffect(() => { void load(); }, [load]);
  async function send(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const result = await api<Notification>("/api/v1/transport/notifications/send", { method: "POST", body: JSON.stringify(Object.fromEntries(data)) }); setMessage(result.status === "encolada" ? "Notificacion encolada." : "Notificacion registrada; canal pendiente de entrega."); event.currentTarget.reset(); await load(); }
  return <div className="space-y-5"><header><p className="text-xs font-semibold uppercase tracking-wide text-apex">Comunicaciones TMS</p><h1 className="mt-1 text-3xl font-semibold">Notificaciones</h1><p className="mt-2 text-sm text-neutral-600">Historial durable de avisos automáticos y manuales.</p></header>{message ? <div className="rounded-md bg-amber-50 p-3 text-sm">{message}</div> : null}<form className="grid gap-3 rounded-xl border border-line bg-white p-4 md:grid-cols-2" onSubmit={send}><h2 className="font-semibold md:col-span-2">Enviar aviso manual</h2><select className={field} name="channel"><option value="email">Correo</option><option value="push">Push</option><option value="sms">SMS</option></select><input className={field} name="recipient" placeholder="Destinatario" required /><input className={field} name="event_type" placeholder="Tipo de evento" required /><input className={field} name="subject" placeholder="Asunto" /><textarea className="min-h-24 rounded-md border border-line p-3 text-sm md:col-span-2" name="body" placeholder="Mensaje" required /><button className="h-10 rounded-md bg-apex px-4 text-sm font-semibold text-white disabled:opacity-40 md:col-span-2" disabled={!canWrite}>Registrar y enviar</button></form><section className="overflow-hidden rounded-xl border border-line bg-white"><div className="border-b border-line p-4 font-semibold">Registro</div><div className="divide-y divide-line">{rows.map((row) => <article className="grid gap-2 p-4 md:grid-cols-[120px_1fr_160px]" key={row.id}><div><strong className="text-sm">{row.channel}</strong><p className="text-xs text-neutral-500">{row.status}</p></div><div><p className="font-medium">{row.subject || row.event_type}</p><p className="text-sm text-neutral-600">{row.body}</p><p className="text-xs text-neutral-500">{row.recipient}{row.error ? ` · ${row.error}` : ""}</p></div><time className="text-xs text-neutral-500">{new Date(row.created_at).toLocaleString()}</time></article>)}</div></section></div>;
}
