type Party = { legal_name?: string; identification_type?: string; identification?: string; email?: string; address?: string; city?: string; phone?: string; whatsapp?: string };
type Advisor = { name?: string; code?: string; phone?: string; email?: string };
type Line = { product_code: string; product_name: string; quantity: number | string; unit_price: number | string; discount?: number | string; line_total: number | string };
export type CommercialDocument = { kind: "COTIZACION" | "PEDIDO"; number: string; date: string; valid_until?: string; status: string; customer: Party; advisor: Advisor; lines: Line[]; subtotal: number | string; discount: number | string; total: number | string; notes?: string };
const clean = (value: unknown, max = 120) => String(value ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^\x20-\x7E]/g, "").slice(0, max);
const escapePdf = (value: unknown) => clean(value).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
const money = (value: unknown) => `$${Number(value || 0).toLocaleString("es-CO", { maximumFractionDigits: 2 })}`;
export function buildCommercialDocumentPdf(data: CommercialDocument) { const width = 595, height = 842, margin = 36; const commands: string[] = []; const text = (v: unknown, x: number, y: number, size = 9, bold = false, color = "0.12 0.14 0.16") => commands.push(`BT /${bold ? "F2" : "F1"} ${size} Tf ${color} rg ${x} ${y} Td (${escapePdf(v)}) Tj ET`); const rect = (x: number, y: number, w: number, h: number, fill = "1 1 1", stroke = "0.78 0.82 0.81") => commands.push(`q ${fill} rg ${stroke} RG ${x} ${y} ${w} ${h} re B Q`);
  rect(0, height - 96, width, 96, "0.03 0.18 0.16", "0.03 0.18 0.16"); text("APEX OS", margin, height - 40, 20, true, "1 1 1"); text(data.kind, margin, height - 68, 13, true, "0.55 0.94 0.86"); text(data.number, 420, height - 52, 14, true, "1 1 1"); let y = height - 122;
  rect(margin, y - 112, width - margin * 2, 118, "0.96 0.98 0.97"); text("CLIENTE", margin + 12, y - 14, 7, true, "0.03 0.35 0.31"); text(data.customer.legal_name || "Cliente", margin + 12, y - 31, 11, true); text(`${data.customer.identification_type || "Documento"}: ${data.customer.identification || "No registrado"}`, margin + 12, y - 48); text(`Correo: ${data.customer.email || "No registrado"}`, margin + 12, y - 64); text(`Direccion: ${data.customer.address || "No registrada"} ${data.customer.city || ""}`, margin + 12, y - 80); text(`Celular: ${data.customer.whatsapp || data.customer.phone || "No registrado"}`, margin + 12, y - 96); text("ASESOR", 350, y - 14, 7, true, "0.03 0.35 0.31"); text(data.advisor.name || "Asesor", 350, y - 31, 10, true); text(`Codigo: ${data.advisor.code || "-"}`, 350, y - 48); text(`Telefono: ${data.advisor.phone || "No registrado"}`, 350, y - 64); text(`Fecha: ${new Date(data.date).toLocaleDateString("es-CO")}`, 350, y - 80); if (data.valid_until) text(`Vigente hasta: ${new Date(data.valid_until).toLocaleDateString("es-CO")}`, 350, y - 96); y -= 140;
  const widths = [70, 205, 55, 85, 98]; ["Codigo", "Producto", "Cant.", "Precio", "Total"].forEach((label, i) => { const x = margin + widths.slice(0, i).reduce((a, b) => a + b, 0); rect(x, y - 24, widths[i], 25, "0.08 0.42 0.38", "0.08 0.42 0.38"); text(label, x + 5, y - 15, 7, true, "1 1 1"); }); y -= 28; data.lines.slice(0, 16).forEach((line, i) => { const values = [line.product_code, line.product_name, line.quantity, money(line.unit_price), money(line.line_total)]; values.forEach((value, c) => { const x = margin + widths.slice(0, c).reduce((a, b) => a + b, 0); rect(x, y - 23, widths[c], 25, i % 2 ? "0.97 0.98 0.97" : "1 1 1"); text(value, x + 5, y - 14, 7.5); }); y -= 25; }); y -= 18; text(`Subtotal: ${money(data.subtotal)}`, 390, y, 9); text(`Descuento: ${money(data.discount)}`, 390, y - 18, 9); text(`TOTAL: ${money(data.total)}`, 390, y - 40, 12, true, "0.03 0.35 0.31"); text(`Observaciones: ${data.notes || "Sin observaciones"}`, margin, y, 8); text("Documento generado por APEX OS", margin, 24, 7, false, "0.35 0.39 0.4");
  const stream = commands.join("\n"); const objects = ["", "<< /Type /Catalog /Pages 2 0 R >>", "<< /Type /Pages /Kids [3 0 R] /Count 1 >>", `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${width} ${height}] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>`, `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>", "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>"]; let pdf = "%PDF-1.4\n"; const offsets = [0]; for (let i = 1; i < objects.length; i += 1) { offsets[i] = pdf.length; pdf += `${i} 0 obj\n${objects[i]}\nendobj\n`; } const xref = pdf.length; pdf += `xref\n0 ${objects.length}\n0000000000 65535 f \n`; for (let i = 1; i < objects.length; i += 1) pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`; pdf += `trailer << /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`; return new TextEncoder().encode(pdf); }
export function downloadCommercialDocumentPdf(data: CommercialDocument) { const url = URL.createObjectURL(new Blob([buildCommercialDocumentPdf(data)], { type: "application/pdf" })); const link = document.createElement("a"); link.href = url; link.download = `${data.kind}-${clean(data.number, 50)}.pdf`; link.click(); URL.revokeObjectURL(url); }
