const tenancy = require("../../middleware/tenancy");
const { requirePermission } = require("../../middleware/rbac");
const schemas = require("./schema");
const service = require("./service");

async function routes(fastify) {
  fastify.addHook("preHandler", fastify.authenticate);
  fastify.addHook("preHandler", tenancy);
  const read = requirePermission("commercial-management", "read");
  const write = requirePermission("commercial-management", "write");
  fastify.get("/commercial-management/reports/quotation-comparison", { preHandler: read, schema: { querystring: { type: "object", required: ["year"], properties: { year: { type: "integer", minimum: 2000, maximum: 2100 } } } } }, r => service.quotationComparisonReport(r.user.tenant_id, r.user, r.query.year));
  fastify.get("/commercial-management/visits/:id/history", { preHandler: read }, r => service.visitTimeline(r.user.tenant_id, r.user, r.params.id, true));
fastify.get("/commercial-management/reports/advisors", { preHandler: read, schema: { querystring: { type: "object", required: ["year"], properties: { year: { type: "integer", minimum: 2000, maximum: 2100 }, month: { type: "integer", minimum: 1, maximum: 12 }, day: { type: "integer", minimum: 1, maximum: 31 }, advisor_id: { type: "integer", minimum: 1 }, group: { type: "string", enum: ["advisor", "day", "week", "month", "year"] } } } } }, r => service.advisorReport(r.user.tenant_id, r.user, r.query));
  fastify.get("/commercial-management/advisors", { preHandler: read }, (r) => service.listAdvisors(r.user.tenant_id, r.user));
  fastify.post("/commercial-management/advisors", { schema: schemas.advisor, preHandler: write }, async (r, reply) => reply.code(201).send(await service.createAdvisor(r.user.tenant_id, r.user, r.body)));
  fastify.patch("/commercial-management/advisors/:id", { schema: schemas.advisorUpdate, preHandler: write }, (r) => service.updateAdvisor(r.user.tenant_id, r.user, r.params.id, r.body));
  fastify.get("/commercial-management/zones", { preHandler: read }, (r) => service.listZones(r.user.tenant_id, r.query));
  fastify.post("/commercial-management/zones", { schema: schemas.zone, preHandler: write }, async (r, reply) => reply.code(201).send(await service.createZone(r.user.tenant_id, r.user, r.body)));
  fastify.patch("/commercial-management/zones/:id", { schema: schemas.zone, preHandler: write }, (r) => service.updateZone(r.user.tenant_id, r.user, r.params.id, r.body));
  fastify.get("/commercial-management/customer-categories", { preHandler: read }, (r) => service.listCustomerCategories(r.user.tenant_id, r.query));
  fastify.post("/commercial-management/customer-categories", { schema: schemas.category, preHandler: write }, async (r, reply) => reply.code(201).send(await service.createCustomerCategory(r.user.tenant_id, r.user, r.body)));
  fastify.patch("/commercial-management/customer-categories/:id", { schema: schemas.category, preHandler: write }, (r) => service.updateCustomerCategory(r.user.tenant_id, r.user, r.params.id, r.body));
  fastify.get("/commercial-management/visit-reasons", { preHandler: read }, (r) => service.listVisitReasons(r.user.tenant_id, r.query));
  fastify.post("/commercial-management/visit-reasons", { schema: schemas.visitReason, preHandler: write }, async (r, reply) => reply.code(201).send(await service.createVisitReason(r.user.tenant_id, r.user, r.body)));
  fastify.patch("/commercial-management/visit-reasons/:id", { schema: schemas.visitReason, preHandler: write }, (r) => service.updateVisitReason(r.user.tenant_id, r.user, r.params.id, r.body));
  fastify.get("/commercial-management/visit-results", { preHandler: read }, (r) => service.listVisitResults(r.user.tenant_id, r.query));
  fastify.post("/commercial-management/visit-results", { schema: schemas.visitResult, preHandler: write }, async (r, reply) => reply.code(201).send(await service.createVisitResult(r.user.tenant_id, r.user, r.body)));
  fastify.patch("/commercial-management/visit-results/:id", { schema: schemas.visitResult, preHandler: write }, (r) => service.updateVisitResult(r.user.tenant_id, r.user, r.params.id, r.body));
  fastify.get("/commercial-management/settings", { preHandler: read }, (r) => service.getSettings(r.user.tenant_id));
  fastify.put("/commercial-management/settings", { schema: schemas.settings, preHandler: write }, (r) => service.updateSettings(r.user.tenant_id, r.user, r.body));
  fastify.get("/commercial-management/customers", { preHandler: read }, (r) => service.listCustomers(r.user.tenant_id, r.user));
  fastify.post("/commercial-management/customers", { schema: schemas.customer, preHandler: write }, async (r, reply) => reply.code(201).send(await service.createCustomer(r.user.tenant_id, r.user, r.body)));
  fastify.patch("/commercial-management/customers/:id", { schema: schemas.customerUpdate, preHandler: write }, (r) => service.updateCustomer(r.user.tenant_id, r.user, r.params.id, r.body));
  fastify.get("/commercial-management/customers/:id/overview", { preHandler: read }, (r) => service.customerOverview(r.user.tenant_id, r.user, r.params.id, r.query.period_id));
  fastify.get("/commercial-management/commitments", { preHandler: read }, (r) => service.listCommitments(r.user.tenant_id, r.user, r.query));
  fastify.post("/commercial-management/customers/:id/commitments", { schema: schemas.commitmentCreate, preHandler: write }, async (r, reply) => reply.code(201).send(await service.createCommitment(r.user.tenant_id, r.user, r.params.id, r.body)));
  fastify.patch("/commercial-management/commitments/:id/status", { schema: schemas.commitmentStatus, preHandler: write }, (r) => service.changeCommitmentStatus(r.user.tenant_id, r.user, r.params.id, r.body.status));
  fastify.get("/commercial-management/products", { preHandler: read }, (r) => service.listProducts(r.user.tenant_id, r.query));
  fastify.post("/commercial-management/products", { schema: schemas.product, preHandler: write }, async (r, reply) => reply.code(201).send(await service.createProduct(r.user.tenant_id, r.user, r.body)));
  fastify.patch("/commercial-management/products/:id", { schema: schemas.productUpdate, preHandler: write }, (r) => service.updateProduct(r.user.tenant_id, r.user, r.params.id, r.body));
  fastify.post("/commercial-management/products/import", { preHandler: write }, async (r) => { const file = await r.file(); if (!file) { const error = new Error("Adjunta la plantilla de productos."); error.statusCode = 400; throw error; } return service.importProducts(r.user.tenant_id, r.user, await file.toBuffer()); });
  fastify.get("/commercial-management/periods", { preHandler: read }, (r) => service.listPeriods(r.user.tenant_id));
  fastify.post("/commercial-management/periods", { schema: schemas.period, preHandler: write }, async (r, reply) => reply.code(201).send(await service.createPeriod(r.user.tenant_id, r.user, r.body)));
  fastify.put("/commercial-management/budgets/advisors", { schema: schemas.budget, preHandler: write }, (r) => service.upsertAdvisorBudget(r.user.tenant_id, r.user, r.body));
  fastify.put("/commercial-management/budgets/customers", { schema: schemas.budget, preHandler: write }, (r) => service.upsertCustomerBudget(r.user.tenant_id, r.user, r.body));
  fastify.get("/commercial-management/budgets", { preHandler: read }, (r) => service.listBudgets(r.user.tenant_id, r.user, r.query));
  fastify.get("/commercial-management/my-day", { preHandler: read }, (r) => service.myDay(r.user.tenant_id, r.user, r.query));
  fastify.post("/commercial-management/visits/check-availability", { schema: schemas.visitAvailability, preHandler: write }, (r) => service.checkVisitAvailability(r.user.tenant_id, r.user, r.body));
  fastify.post("/commercial-management/visits", { schema: schemas.visit, preHandler: write }, async (r, reply) => reply.code(201).send(await service.createVisit(r.user.tenant_id, r.user, r.body)));
  fastify.get("/commercial-management/visits", { preHandler: read }, (r) => service.listVisits(r.user.tenant_id, r.user, r.query));
  fastify.get("/commercial-management/visits/report", { preHandler: read }, (r) => service.visitReport(r.user.tenant_id, r.user, r.query));
  fastify.get("/commercial-management/visits/:id/timeline", { preHandler: read }, (r) => service.visitTimeline(r.user.tenant_id, r.user, r.params.id));
  fastify.post("/commercial-management/visits/:id/customer", { schema: { body: { ...schemas.customer.body, required: ["code", "legal_name", "category_id"] } }, preHandler: write }, async (r, reply) => reply.code(201).send(await service.createVisitCustomer(r.user.tenant_id, r.user, r.params.id, r.body)));
  fastify.patch("/commercial-management/visits/:id/start", { preHandler: write }, (r) => service.startVisit(r.user.tenant_id, r.user, r.params.id));
  fastify.patch("/commercial-management/visits/:id/complete", { schema: schemas.visitComplete, preHandler: write }, (r) => service.completeVisit(r.user.tenant_id, r.user, r.params.id, r.body));
  fastify.post("/commercial-management/visits/:id/reschedule", { schema: schemas.visitReschedule, preHandler: write }, async (r, reply) => reply.code(201).send(await service.rescheduleVisit(r.user.tenant_id, r.user, r.params.id, r.body)));
  fastify.get("/commercial-management/quotations", { preHandler: read }, (r) => service.listQuotations(r.user.tenant_id, r.user, r.query));
  fastify.get("/commercial-management/quotations/:id", { preHandler: read }, (r) => service.getQuotation(r.user.tenant_id, r.user, r.params.id));
  fastify.post("/commercial-management/quotations/:id/cancel", { schema: { body: { type: "object", required: ["reason"], properties: { reason: { type: "string", minLength: 1, maxLength: 2000 } } } }, preHandler: write }, (r) => service.cancelQuotation(r.user.tenant_id, r.user, r.params.id, r.body.reason));
  fastify.post("/commercial-management/quotations", { schema: schemas.quotation, preHandler: write }, async (r, reply) => reply.code(201).send(await service.createQuotation(r.user.tenant_id, r.user, r.body)));
  fastify.post("/commercial-management/quotations/:id/convert-to-order", { preHandler: write }, async (r, reply) => reply.code(201).send(await service.convertQuotationToOrder(r.user.tenant_id, r.user, r.params.id, r.body || {})));
  fastify.get("/commercial-management/orders", { preHandler: read }, (r) => service.listOrders(r.user.tenant_id, r.user, r.query));
  fastify.get("/commercial-management/orders/:id", { preHandler: read }, (r) => service.getOrder(r.user.tenant_id, r.user, r.params.id));
  fastify.post("/commercial-management/orders", { schema: schemas.order, preHandler: write }, async (r, reply) => reply.code(201).send(await service.createOrder(r.user.tenant_id, r.user, r.body)));
  fastify.patch("/commercial-management/orders/:id/status", { schema: schemas.orderStatus, preHandler: write }, (r) => service.changeOrderStatus(r.user.tenant_id, r.user, r.params.id, r.body.status));
  fastify.get("/commercial-management/dashboard", { preHandler: read }, (r) => service.dashboard(r.user.tenant_id, r.user, r.query.period_id));
}

module.exports = routes;
