"use client";

import { api } from "@/lib/api";
import { hasStoredRolePermission } from "@/lib/rolePermissions";
import { AlertTriangle, ArrowRight, Boxes, ClipboardCheck, MapPinned, Plus, RefreshCw, Truck } from "lucide-react";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Point = { id: number; code: string; name: string; address: string; city: string; window_start?: string; window_end?: string };
type Origin = { id: number; code: string; name: string; city: string };
type Need = { id: number; code: string; origin_id?: number; origin_name: string; status: string; priority: string; due_at: string; weight_kg: number; volume_m3: number; pallets: number; delivery_point: Point; validation_errors?: string[] };
type Carrier = { id: number; legal_name: string };
type Driver = { id: number; name: string; carrier_id?: number };
type Vehicle = { id: number; plate: string; master_status: string; capacity_value?: number; capacity_unit?: string };
type Stop = { id: number; sequence: number; status: string; delivery_point?: Point; attempts?: Array<{ id: number; result: string; attempt_number: number }> };
type Settlement = { id: number; code: string; status: string; liquidated_cost: number; currency: string };
type Trip = { id: number; code: string; status: string; origin_name: string; planned_departure?: string; total_weight_kg: number; total_volume_m3: number; total_pallets: number; estimated_cost: number; committed_cost: number; actual_cost: number; currency: string; vehicle_plate?: string; driver?: Driver; carrier?: Carrier; stops: Stop[]; settlements?: Settlement[]; needs?: unknown[] };
type Tower = { total: number; normal: number; at_risk: number; in_execution: number; pending_delivery: number; trips: Trip[] };

const inputClass = "h-10 w-full rounded-md border border-line bg-white px-3 text-sm outline-none focus:border-apex";
const NEXT_STATUS: Record<string, string> = { asignado: "en_cargue", en_cargue: "despachado", despachado: "en_transito", en_transito: "entregado", entregado: "cerrado" };

export default function TransportOperationPage() {
  const [tower, setTower] = useState<Tower>({ total: 0, normal: 0, at_risk: 0, in_execution: 0, pending_delivery: 0, trips: [] });
  const [needs, setNeeds] = useState<Need[]>([]); const [points, setPoints] = useState<Point[]>([]); const [origins, setOrigins] = useState<Origin[]>([]); const [carriers, setCarriers] = useState<Carrier[]>([]);
  const [drivers, setDrivers] = useState<Driver[]>([]); const [vehicles, setVehicles] = useState<Vehicle[]>([]); const [selected, setSelected] = useState<Trip | null>(null);
  const [modal, setModal] = useState<"need" | "trip" | null>(null); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  const canWrite = hasStoredRolePermission("transport", "write");

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const [towerData, needRows, pointRows, originRows, carrierRows, driverRows, vehicleRows] = await Promise.all([
        api<Tower>("/api/v1/transport/control-tower"), api<Need[]>("/api/v1/transport/needs"), api<Point[]>("/api/v1/transport/delivery-points"),
        api<Origin[]>("/api/v1/transport/origins"), api<Carrier[]>("/api/v1/transport/carriers"), api<Driver[]>("/api/v1/transport/drivers?status=disponible"), api<Vehicle[]>("/api/v1/transport/vehicles")
      ]);
      setTower(towerData); setNeeds(needRows); setPoints(pointRows); setOrigins(originRows); setCarriers(carrierRows); setDrivers(driverRows); setVehicles(vehicleRows); setMessage("");
    } catch (error) { setMessage(error instanceof Error ? error.message : "No fue posible cargar la operacion TMS."); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => { void load(); }, [load]);

  async function openTrip(id: number) { const detail = await api<Trip>(`/api/v1/transport/trips/${id}`); setSelected(detail); }
  async function refreshSelected(id: number) { const detail = await api<Trip>(`/api/v1/transport/trips/${id}`); setSelected(detail); await load(); }

  async function createNeed(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    const origin = origins.find((row) => row.id === Number(data.get("origin_id")));
    await api("/api/v1/transport/needs", { method: "POST", body: JSON.stringify({ code: data.get("code"), source_type: data.get("source_type") || "manual", source_reference: data.get("source_reference"), origin_id: origin?.id, origin_name: origin?.name, delivery_point_id: Number(data.get("delivery_point_id")), available_at: data.get("available_at"), due_at: data.get("due_at"), priority: data.get("priority"), service_level: data.get("service_level"), weight_kg: Number(data.get("weight_kg")), volume_m3: Number(data.get("volume_m3")), pallets: Number(data.get("pallets") || 0), packages: Number(data.get("packages") || 0), cargo_value: Number(data.get("cargo_value") || 0), currency: data.get("currency") || "COP" }) });
    setModal(null); await load(); setMessage("Necesidad de transporte registrada y validada.");
  }

  async function createTrip(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget); const ids = data.getAll("need_ids").map(Number);
    await api("/api/v1/transport/trips", { method: "POST", body: JSON.stringify({ code: data.get("code"), origin_name: data.get("origin_name"), need_ids: ids, planned_departure: data.get("planned_departure") || undefined, planned_arrival: data.get("planned_arrival") || undefined, estimated_cost: Number(data.get("estimated_cost") || 0), currency: data.get("currency") || "COP" }) });
    setModal(null); await load(); setMessage("Viaje planificado con sus paradas.");
  }

  async function assign(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!selected) return; const data = new FormData(event.currentTarget);
    await api(`/api/v1/transport/trips/${selected.id}/assign`, { method: "POST", body: JSON.stringify({ carrier_id: data.get("carrier_id") ? Number(data.get("carrier_id")) : undefined, vehicle_id: Number(data.get("vehicle_id")), driver_id: Number(data.get("driver_id")), committed_cost: Number(data.get("committed_cost") || 0), reason: "Asignacion manual desde torre TMS" }) });
    await refreshSelected(selected.id);
  }

  async function transition(status: string) { if (!selected) return; await api(`/api/v1/transport/trips/${selected.id}/transition`, { method: "POST", body: JSON.stringify({ status }) }); await refreshSelected(selected.id); }

  async function registerAttempt(event: FormEvent<HTMLFormElement>, stop: Stop) {
    event.preventDefault(); if (!selected) return; const data = new FormData(event.currentTarget); const result = String(data.get("result"));
    const complete = ["completa", "parcial"].includes(result);
    await api(`/api/v1/transport/trips/${selected.id}/stops/${stop.id}/attempts`, { method: "POST", body: JSON.stringify({ result, cause_code: data.get("cause_code"), responsible: data.get("responsible"), additional_cost: Number(data.get("additional_cost") || 0), recoverable: data.get("recoverable") === "on", next_attempt_at: data.get("next_attempt_at") || undefined, observations: data.get("observations"), evidence: [], delivered_lines: [], ...(complete ? { pod: { received_at: new Date().toISOString(), receiver_name: data.get("receiver_name"), receiver_document: data.get("receiver_document"), photos: [] } } : {}) }) });
    await refreshSelected(selected.id);
  }

  async function createBasicSettlement() {
    if (!selected) return; const base = Number(selected.committed_cost || selected.estimated_cost || 0);
    const attempts = selected.stops.flatMap((stop) => stop.attempts || []); void attempts;
    const result = await api<Settlement>(`/api/v1/transport/trips/${selected.id}/settlements`, { method: "POST", body: JSON.stringify({ code: `LIQ-${selected.code}`, currency: selected.currency, lines: [{ concept: "FLETE_BASE", quantity: 1, unit_rate: base, total: base, source: "viaje" }] }) });
    setMessage(`Liquidacion ${result.code} creada.`); await refreshSelected(selected.id);
  }

  async function approveSettlement(id: number) { if (!selected) return; await api(`/api/v1/transport/settlements/${id}/approve`, { method: "POST" }); await refreshSelected(selected.id); }

  const plannable = useMemo(() => needs.filter((need) => need.status === "pendiente"), [needs]);

  return <div className="space-y-5">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-apex">Operacion integral</p><h1 className="mt-1 text-3xl font-semibold">Torre de transporte</h1><p className="mt-2 text-sm text-neutral-600">De la necesidad al viaje, entrega y liquidacion.</p></div><div className="flex gap-2"><button className="inline-flex h-10 items-center gap-2 rounded-md border border-line bg-white px-3 text-sm font-semibold" onClick={() => void load()}><RefreshCw size={16} />Actualizar</button>{canWrite ? <><button className="inline-flex h-10 items-center gap-2 rounded-md border border-apex px-3 text-sm font-semibold text-apex" onClick={() => setModal("need")}><Plus size={16} />Necesidad</button><button className="inline-flex h-10 items-center gap-2 rounded-md bg-apex px-3 text-sm font-semibold text-white" onClick={() => setModal("trip")}><Truck size={16} />Planear viaje</button></> : null}</div></header>
    {message ? <div className="rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">{message}</div> : null}
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><Metric label="Viajes abiertos" value={tower.total} icon={<Truck size={18} />} /><Metric label="En ejecucion" value={tower.in_execution} icon={<MapPinned size={18} />} /><Metric label="En riesgo" value={tower.at_risk} icon={<AlertTriangle size={18} />} /><Metric label="Paradas pendientes" value={tower.pending_delivery} icon={<ClipboardCheck size={18} />} /><Metric label="Necesidades listas" value={plannable.length} icon={<Boxes size={18} />} /></div>
    <div className="grid gap-4 xl:grid-cols-[1.4fr_1fr]">
      <section className="overflow-hidden rounded-xl border border-line bg-white"><div className="border-b border-line px-4 py-3"><h2 className="font-semibold">Viajes activos</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-paper text-xs uppercase text-neutral-500"><tr><th className="px-4 py-3">Viaje</th><th className="px-4 py-3">Estado</th><th className="px-4 py-3">Recurso</th><th className="px-4 py-3">Carga</th><th className="px-4 py-3"></th></tr></thead><tbody>{tower.trips.map((trip) => <tr className="border-t border-line" key={trip.id}><td className="px-4 py-3"><p className="font-semibold">{trip.code}</p><p className="text-xs text-neutral-500">{trip.origin_name} · {trip.stops.length} paradas</p></td><td className="px-4 py-3"><Status value={trip.status} /></td><td className="px-4 py-3">{trip.vehicle_plate || "Sin asignar"}<p className="text-xs text-neutral-500">{trip.driver?.name || "Sin conductor"}</p></td><td className="px-4 py-3">{trip.total_weight_kg.toLocaleString()} kg<p className="text-xs text-neutral-500">{trip.total_volume_m3} m3 · {trip.total_pallets} pallets</p></td><td className="px-4 py-3 text-right"><button className="font-semibold text-apex" onClick={() => void openTrip(trip.id)}>Gestionar</button></td></tr>)}{!tower.trips.length ? <tr><td className="px-4 py-8 text-center text-neutral-500" colSpan={5}>No hay viajes abiertos.</td></tr> : null}</tbody></table></div></section>
      <section className="rounded-xl border border-line bg-white p-4"><h2 className="font-semibold">Demanda por planear</h2><div className="mt-3 space-y-2">{needs.slice(0, 12).map((need) => <div className="rounded-md border border-line p-3" key={need.id}><div className="flex justify-between gap-2"><p className="font-semibold">{need.code}</p><Status value={need.status} /></div><p className="mt-1 text-sm">{need.delivery_point?.name}</p><p className="text-xs text-neutral-500">{need.weight_kg} kg · {need.volume_m3} m3 · vence {new Date(need.due_at).toLocaleString()}</p>{need.validation_errors?.length ? <p className="mt-1 text-xs text-rose-700">{need.validation_errors.join(", ")}</p> : null}</div>)}</div></section>
    </div>
    {loading ? <p className="text-sm text-neutral-500">Actualizando operacion...</p> : null}
    {modal ? <div className="fixed inset-0 z-50 grid place-items-center bg-black/35 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-auto rounded-xl bg-white p-5"><div className="mb-4 flex justify-between"><h2 className="text-xl font-semibold">{modal === "need" ? "Nueva necesidad" : "Planear viaje"}</h2><button onClick={() => setModal(null)}>Cerrar</button></div>{modal === "need" ? <NeedForm origins={origins} points={points} onSubmit={createNeed} /> : <TripForm needs={plannable} onSubmit={createTrip} />}</div></div> : null}
    {selected ? <TripDrawer trip={selected} carriers={carriers} drivers={drivers} vehicles={vehicles} onClose={() => setSelected(null)} onAssign={assign} onTransition={transition} onAttempt={registerAttempt} onCreateSettlement={createBasicSettlement} onApproveSettlement={approveSettlement} /> : null}
  </div>;
}

function NeedForm({ origins, points, onSubmit }: { origins: Origin[]; points: Point[]; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form className="grid gap-3 sm:grid-cols-2" onSubmit={onSubmit}><Field name="code" label="Codigo" required /><Field name="source_reference" label="Pedido/entrega origen" /><Field name="source_type" label="Tipo de origen" defaultValue="manual" required /><label className="text-sm"><span className="mb-1 block font-medium">Origen operativo</span><select className={inputClass} name="origin_id" required><option value="">Seleccionar</option>{origins.map((origin) => <option key={origin.id} value={origin.id}>{origin.code} · {origin.name}</option>)}</select></label><label className="text-sm sm:col-span-2"><span className="mb-1 block font-medium">Punto de entrega</span><select className={inputClass} name="delivery_point_id" required><option value="">Seleccionar</option>{points.map((point) => <option key={point.id} value={point.id}>{point.code} · {point.name} · {point.city}</option>)}</select></label><Field name="available_at" label="Disponible desde" type="datetime-local" required /><Field name="due_at" label="Fecha limite" type="datetime-local" required /><Field name="weight_kg" label="Peso kg" type="number" step="any" required /><Field name="volume_m3" label="Volumen m3" type="number" step="any" required /><Field name="pallets" label="Pallets" type="number" step="any" defaultValue="0" /><Field name="packages" label="Bultos" type="number" defaultValue="0" /><Field name="cargo_value" label="Valor mercancia" type="number" step="any" defaultValue="0" /><Field name="currency" label="Moneda" defaultValue="COP" /><label className="text-sm"><span className="mb-1 block font-medium">Prioridad</span><select className={inputClass} name="priority"><option>normal</option><option>alta</option><option>urgente</option></select></label><label className="text-sm"><span className="mb-1 block font-medium">Servicio</span><select className={inputClass} name="service_level"><option>normal</option><option>express</option><option>refrigerado</option></select></label><Submit label="Crear necesidad" /></form>; }
function TripForm({ needs, onSubmit }: { needs: Need[]; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { const origins = [...new Set(needs.map((need) => need.origin_name))]; return <form className="grid gap-3 sm:grid-cols-2" onSubmit={onSubmit}><Field name="code" label="Codigo de viaje" required /><label className="text-sm"><span className="mb-1 block font-medium">Origen</span><select className={inputClass} name="origin_name" required><option value="">Seleccionar</option>{origins.map((origin) => <option key={origin}>{origin}</option>)}</select></label><Field name="planned_departure" label="Salida planificada" type="datetime-local" /><Field name="planned_arrival" label="Llegada estimada" type="datetime-local" /><Field name="estimated_cost" label="Costo estimado" type="number" step="any" defaultValue="0" /><Field name="currency" label="Moneda" defaultValue="COP" /><fieldset className="sm:col-span-2"><legend className="mb-2 text-sm font-medium">Necesidades compatibles</legend><div className="max-h-64 space-y-2 overflow-auto rounded-md border border-line p-3">{needs.map((need) => <label className="flex items-center justify-between gap-3 text-sm" key={need.id}><span><input className="mr-2" name="need_ids" type="checkbox" value={need.id} />{need.code} · {need.delivery_point?.name}</span><span className="text-xs text-neutral-500">{need.weight_kg} kg</span></label>)}</div></fieldset><Submit label="Crear plan y paradas" /></form>; }

function TripDrawer({ trip, carriers, drivers, vehicles, onClose, onAssign, onTransition, onAttempt, onCreateSettlement, onApproveSettlement }: { trip: Trip; carriers: Carrier[]; drivers: Driver[]; vehicles: Vehicle[]; onClose: () => void; onAssign: (event: FormEvent<HTMLFormElement>) => void; onTransition: (status: string) => void; onAttempt: (event: FormEvent<HTMLFormElement>, stop: Stop) => void; onCreateSettlement: () => void; onApproveSettlement: (id: number) => void }) {
  const next = NEXT_STATUS[trip.status]; const allStopsDone = trip.stops.every((stop) => ["completa", "parcial"].includes(stop.status)); const approved = trip.settlements?.some((row) => row.status === "aprobada");
  return <div className="fixed inset-0 z-50 flex justify-end bg-black/35"><aside className="h-full w-full max-w-2xl overflow-auto bg-white p-5 shadow-xl"><div className="flex justify-between"><div><p className="text-xs font-semibold uppercase text-apex">Viaje {trip.code}</p><h2 className="text-2xl font-semibold">{trip.origin_name}</h2><Status value={trip.status} /></div><button className="self-start" onClick={onClose}>Cerrar</button></div><div className="mt-4 grid grid-cols-3 gap-2"><Mini label="Peso" value={`${trip.total_weight_kg} kg`} /><Mini label="Volumen" value={`${trip.total_volume_m3} m3`} /><Mini label="Costo" value={`${trip.currency} ${Number(trip.actual_cost || trip.committed_cost || trip.estimated_cost).toLocaleString()}`} /></div>
    {trip.status === "planificado" ? <form className="mt-5 grid gap-3 rounded-xl border border-line bg-paper p-4 sm:grid-cols-2" onSubmit={onAssign}><h3 className="font-semibold sm:col-span-2">Asignacion manual</h3><label className="text-sm"><span className="mb-1 block">Transportadora</span><select className={inputClass} name="carrier_id"><option value="">Flota propia</option>{carriers.map((row) => <option key={row.id} value={row.id}>{row.legal_name}</option>)}</select></label><label className="text-sm"><span className="mb-1 block">Vehiculo</span><select className={inputClass} name="vehicle_id" required><option value="">Seleccionar</option>{vehicles.map((row) => <option key={row.id} value={row.id}>{row.plate} · {row.master_status}</option>)}</select></label><label className="text-sm"><span className="mb-1 block">Conductor</span><select className={inputClass} name="driver_id" required><option value="">Seleccionar</option>{drivers.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><Field name="committed_cost" label="Costo comprometido" type="number" step="any" defaultValue={String(trip.estimated_cost || 0)} /><Submit label="Asignar recursos" /></form> : null}
    <section className="mt-5"><h3 className="font-semibold">Paradas y entrega</h3><div className="mt-2 space-y-3">{trip.stops.map((stop) => <div className="rounded-lg border border-line p-3" key={stop.id}><div className="flex justify-between"><div><p className="font-semibold">{stop.sequence}. {stop.delivery_point?.name || "Parada"}</p><p className="text-xs text-neutral-500">{stop.delivery_point?.address} · {stop.delivery_point?.city}</p></div><Status value={stop.status} /></div>{trip.status === "en_transito" && !["completa", "parcial"].includes(stop.status) ? <form className="mt-3 grid gap-2 sm:grid-cols-2" onSubmit={(event) => onAttempt(event, stop)}><label className="text-xs">Resultado<select className={inputClass} name="result"><option value="completa">Completa</option><option value="parcial">Parcial</option><option value="cliente_cerrado">Cliente cerrado</option><option value="rechazada">Rechazada</option><option value="direccion_incorrecta">Direccion incorrecta</option><option value="averia">Averia</option></select></label><Field name="receiver_name" label="Receptor (POD)" /><Field name="receiver_document" label="Documento receptor" /><Field name="cause_code" label="Causa de novedad" /><Field name="responsible" label="Responsable" /><Field name="additional_cost" label="Costo adicional" type="number" defaultValue="0" /><Field name="next_attempt_at" label="Proximo intento" type="datetime-local" /><label className="flex items-center gap-2 pt-6 text-sm"><input name="recoverable" type="checkbox" />Costo recuperable</label><Submit label="Registrar resultado" /></form> : null}</div>)}</div></section>
    {trip.status === "entregado" ? <section className="mt-5 rounded-xl border border-line p-4"><h3 className="font-semibold">Liquidacion</h3>{trip.settlements?.length ? trip.settlements.map((row) => <div className="mt-2 flex items-center justify-between rounded-md bg-paper p-3" key={row.id}><div><p className="font-semibold">{row.code}</p><p className="text-xs">{row.currency} {Number(row.liquidated_cost).toLocaleString()} · {row.status}</p></div>{row.status === "borrador" ? <button className="rounded-md bg-apex px-3 py-2 text-sm font-semibold text-white" onClick={() => onApproveSettlement(row.id)}>Aprobar</button> : null}</div>) : <button className="mt-3 rounded-md border border-apex px-3 py-2 text-sm font-semibold text-apex" onClick={onCreateSettlement}>Crear liquidacion basica</button>}</section> : null}
    {next ? <div className="sticky bottom-0 mt-6 flex justify-end border-t border-line bg-white py-4"><button className="inline-flex h-10 items-center gap-2 rounded-md bg-apex px-4 text-sm font-semibold text-white disabled:opacity-40" disabled={(next === "entregado" && !allStopsDone) || (next === "cerrado" && !approved)} onClick={() => onTransition(next)}>Avanzar a {next.replaceAll("_", " ")}<ArrowRight size={16} /></button></div> : null}
  </aside></div>;
}

function Metric({ label, value, icon }: { label: string; value: number; icon: React.ReactNode }) { return <div className="rounded-xl border border-line bg-white p-3"><div className="flex items-center justify-between text-neutral-500"><span className="text-xs font-medium">{label}</span>{icon}</div><p className="mt-2 text-2xl font-semibold">{value}</p></div>; }
function Status({ value }: { value: string }) { return <span className="inline-flex rounded-full bg-[#146C6312] px-2 py-1 text-xs font-semibold text-apex">{value.replaceAll("_", " ")}</span>; }
function Mini({ label, value }: { label: string; value: string }) { return <div className="rounded-md bg-paper p-3"><p className="text-xs text-neutral-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
function Field(props: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { const { label, ...input } = props; return <label className="text-sm"><span className="mb-1 block font-medium">{label}</span><input className={inputClass} {...input} /></label>; }
function Submit({ label }: { label: string }) { return <div className="sm:col-span-2 flex justify-end pt-2"><button className="inline-flex h-10 items-center gap-2 rounded-md bg-apex px-4 text-sm font-semibold text-white" type="submit"><Plus size={16} />{label}</button></div>; }
