"use client";

import { api } from "@/lib/api";
import { hasStoredRolePermission } from "@/lib/rolePermissions";
import { FormEvent, useEffect, useState } from "react";

type Config = { timezone: string; default_currency: string; distance_unit: string; weight_unit: string; road_factor: number; gps_interval_seconds: number; gps_retention_days: number; mobile_config: Record<string, unknown>; notification_config: Record<string, unknown> };
const input = "mt-1 h-10 w-full rounded-md border border-line bg-white px-3 text-sm";

export default function TransportConfigurationPage() {
  const [config, setConfig] = useState<Config | null>(null); const [message, setMessage] = useState(""); const canWrite = hasStoredRolePermission("transport", "write");
  useEffect(() => { api<Config>("/api/v1/transport/config").then(setConfig).catch((error) => setMessage(error instanceof Error ? error.message : "No fue posible cargar la configuracion.")); }, []);
  async function save(event: FormEvent<HTMLFormElement>, endpoint: string) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); const payload = Object.fromEntries(Object.entries(values).map(([key, value]) => [key, ["road_factor", "gps_interval_seconds", "gps_retention_days", "max_offline_hours"].includes(key) ? Number(value) : value === "true" ? true : value === "false" ? false : value])); const saved = await api<Config>(endpoint, { method: "PUT", body: JSON.stringify(payload) }); setConfig(saved); setMessage("Configuracion TMS guardada para la empresa activa."); }
  if (!config) return <p className="text-sm text-neutral-500">Cargando configuracion TMS...</p>;
  return <div className="space-y-5"><header><p className="text-xs font-semibold uppercase tracking-wide text-apex">Administracion TMS</p><h1 className="mt-1 text-3xl font-semibold">Configuracion</h1><p className="mt-2 text-sm text-neutral-600">Parametros operativos sincronizados con la torre y la futura app movil.</p></header>{message ? <div className="rounded-md border border-amber-200 bg-amber-50 p-3 text-sm">{message}</div> : null}<div className="grid gap-4 xl:grid-cols-3">
    <Form title="Operacion" onSubmit={(event) => save(event, "/api/v1/transport/config")} disabled={!canWrite}><Field name="timezone" label="Zona horaria" value={config.timezone} /><Field name="default_currency" label="Moneda" value={config.default_currency} /><Field name="distance_unit" label="Unidad distancia" value={config.distance_unit} /><Field name="weight_unit" label="Unidad peso" value={config.weight_unit} /><Field name="road_factor" label="Factor vial" type="number" step="0.01" value={config.road_factor} /><Field name="gps_retention_days" label="Retencion GPS (dias)" type="number" value={config.gps_retention_days} /></Form>
    <Form title="Aplicacion movil" onSubmit={(event) => save(event, "/api/v1/transport/config/mobile")} disabled={!canWrite}><Choice name="tracking_enabled" label="Tracking habilitado" value={config.mobile_config.tracking_enabled} /><Choice name="background_tracking" label="Tracking en segundo plano" value={config.mobile_config.background_tracking} /><Choice name="require_photo" label="Foto obligatoria" value={config.mobile_config.require_photo} /><Choice name="require_signature" label="Firma obligatoria" value={config.mobile_config.require_signature} /><Choice name="allow_offline" label="Operacion offline" value={config.mobile_config.allow_offline} /><Field name="max_offline_hours" label="Maximo offline (horas)" type="number" value={Number(config.mobile_config.max_offline_hours || 24)} /></Form>
    <Form title="Notificaciones" onSubmit={(event) => save(event, "/api/v1/transport/config/notifications")} disabled={!canWrite}><Choice name="email_enabled" label="Correo" value={config.notification_config.email_enabled} /><Choice name="sms_enabled" label="SMS" value={config.notification_config.sms_enabled} /><Choice name="push_enabled" label="Push movil" value={config.notification_config.push_enabled} /><Choice name="notify_on_dispatched" label="Avisar despacho" value={config.notification_config.notify_on_dispatched} /><Choice name="notify_on_delivered" label="Avisar entrega" value={config.notification_config.notify_on_delivered} /><Choice name="notify_on_rejected" label="Avisar rechazo" value={config.notification_config.notify_on_rejected} /></Form>
  </div></div>;
}

function Form({ title, children, onSubmit, disabled }: { title: string; children: React.ReactNode; onSubmit: (event: FormEvent<HTMLFormElement>) => void; disabled: boolean }) { return <form className="rounded-xl border border-line bg-white p-4" onSubmit={onSubmit}><h2 className="mb-3 font-semibold">{title}</h2><div className="space-y-3">{children}</div><button className="mt-4 h-10 rounded-md bg-apex px-4 text-sm font-semibold text-white disabled:opacity-40" disabled={disabled}>Guardar</button></form>; }
function Field({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className="block text-sm"><span className="font-medium">{label}</span><input className={input} {...props} /></label>; }
function Choice({ name, label, value }: { name: string; label: string; value: unknown }) { return <label className="block text-sm"><span className="font-medium">{label}</span><select className={input} defaultValue={value === false ? "false" : "true"} name={name}><option value="true">Si</option><option value="false">No</option></select></label>; }
