"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { ArrowLeft, CalendarCheck2, CheckCircle2, Clock3, FileClock, ListTodo, RefreshCw } from "lucide-react";

type Row = Record<string, any>;
type Dashboard = { totals: { visits: number; scheduled: number; in_progress: number; completed: number; overdue: number; commitments: number; overdue_commitments: number; quotations: number }; visits: Row[]; commitments: Row[]; quotations: Row[] };
const input = "h-10 rounded-md border border-line bg-white px-3 text-sm";
const localDate = () => new Intl.DateTimeFormat("en-CA", { timeZone: "America/Bogota", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
const dateTime = (value: string) => new Intl.DateTimeFormat("es-CO", { timeZone: "America/Bogota", dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const shortDate = (value: string) => new Intl.DateTimeFormat("es-CO", { timeZone: "America/Bogota", dateStyle: "medium" }).format(new Date(value));

export default function MyDayPage() {
  const [date, setDate] = useState(localDate());
  const [advisor, setAdvisor] = useState("");
  const [advisors, setAdvisors] = useState<Row[]>([]);
  const [data, setData] = useState<Dashboard | null>(null);
  const [revision, setRevision] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { let active = true; setLoading(true); setError(""); const query = new URLSearchParams({ date }); if (advisor) query.set("advisor_id", advisor); Promise.all([api<Dashboard>(`/api/v1/commercial-management/my-day?${query}`, { cache: "no-store" }), api<Row[]>("/api/v1/commercial-management/advisors", { cache: "no-store" })]).then(([dashboard, people]) => { if (active) { setData(dashboard); setAdvisors(people); } }).catch(value => { if (active) setError(value instanceof Error ? value.message : "No fue posible cargar Mi día."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [date, advisor, revision]);
  async function toggleCommitment(item: Row) { await api(`/api/v1/commercial-management/commitments/${item.id}/status`, { method: "PATCH", body: JSON.stringify({ status: "COMPLETED" }) }); setRevision(value => value + 1); }
  return <div className="apex-workspace-shell space-y-4">
    <header className="apex-section-card flex flex-wrap items-start justify-between gap-3 p-5"><div><Link className="inline-flex items-center gap-1 text-sm text-apex" href="/dashboard/gestion-comercial"><ArrowLeft size={16}/> Gestión Comercial</Link><h1 className="mt-2 flex items-center gap-2 text-2xl font-semibold"><CalendarCheck2 className="text-apex"/> Mi día</h1><p className="mt-1 text-sm text-neutral-600">Prioriza visitas, compromisos y cotizaciones que requieren seguimiento.</p></div><div className="flex flex-wrap gap-2"><input className={input} type="date" value={date} onChange={event => setDate(event.target.value)}/><select className={input} value={advisor} onChange={event => setAdvisor(event.target.value)}><option value="">Todos mis asesores</option>{advisors.map(person => <option key={person.id} value={person.id}>{person.name}</option>)}</select><button className={`${input} inline-flex items-center gap-2`} onClick={() => setRevision(value => value + 1)}><RefreshCw size={16}/>Actualizar</button></div></header>
    {error && <p role="alert" className="rounded-md bg-red-50 p-4 text-red-700">{error}</p>}{loading && <p role="status">Organizando el día…</p>}
    {data && <><section className="grid grid-cols-2 gap-3 lg:grid-cols-4 xl:grid-cols-7">{[["Visitas", data.totals.visits], ["Agendadas", data.totals.scheduled], ["En curso", data.totals.in_progress], ["Completas", data.totals.completed], ["Vencidas", data.totals.overdue], ["Compromisos", data.totals.commitments], ["Cotizaciones", data.totals.quotations]].map(([label, value]) => <div className="apex-section-card p-4" key={label}><p className="text-xs text-neutral-500">{label}</p><strong className="mt-1 block text-2xl">{value}</strong></div>)}</section>
    <section className="grid gap-4 xl:grid-cols-[1.35fr_1fr]"><div className="apex-section-card overflow-hidden"><div className="flex items-center justify-between p-4"><h2 className="flex items-center gap-2 font-semibold"><Clock3 size={18} className="text-apex"/>Ruta de visitas</h2><Link className="text-sm font-semibold text-apex" href={`/dashboard/gestion-comercial/agenda?fecha=${date}`}>Abrir agenda</Link></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-paper text-xs uppercase text-neutral-500"><tr><th className="p-3">Hora</th><th className="p-3">Cliente</th><th className="p-3">Motivo</th><th className="p-3">Asesor</th><th className="p-3">Acción</th></tr></thead><tbody>{data.visits.map(visit => <tr className="border-t border-line" key={visit.id}><td className="p-3 font-semibold">{dateTime(visit.visit_date).split(",").pop()}</td><td className="p-3"><strong>{visit.customer?.legal_name || "Prospección sin cliente"}</strong><p className="text-xs text-neutral-500">{visit.customer?.city || visit.customer?.address || "Sin ubicación"}</p></td><td className="p-3">{visit.reason?.name || "Sin motivo"}</td><td className="p-3">{visit.advisor?.name}</td><td className="p-3"><Link className="font-semibold text-apex" href={`/dashboard/gestion-comercial/agenda?visita=${visit.id}`}>{visit.status === "IN_PROGRESS" ? "Continuar" : visit.status === "COMPLETED" ? "Ver" : "Gestionar"}</Link></td></tr>)}</tbody></table>{!data.visits.length && <p className="p-8 text-center text-neutral-500">No hay visitas para esta fecha.</p>}</div></div>
    <div className="space-y-4"><div className="apex-section-card p-4"><h2 className="flex items-center gap-2 font-semibold"><ListTodo size={18} className="text-amber-600"/>Compromisos vencidos y del día</h2><div className="mt-3 space-y-2">{data.commitments.map(item => <div className="flex items-start justify-between gap-3 rounded-md bg-amber-50 p-3 text-sm" key={item.id}><div><strong>{item.customer.legal_name}</strong><p>{item.description}</p><span className="text-xs text-amber-800">Vence {shortDate(item.due_date)} · {item.advisor.name}</span></div><button title="Marcar cumplido" className="rounded-md border border-amber-300 bg-white p-2 text-emerald-700" onClick={() => void toggleCommitment(item)}><CheckCircle2 size={17}/></button></div>)}{!data.commitments.length && <p className="py-4 text-sm text-neutral-500">Sin compromisos pendientes para atender.</p>}</div></div>
    <div className="apex-section-card p-4"><h2 className="flex items-center gap-2 font-semibold"><FileClock size={18} className="text-indigo-600"/>Cotizaciones por vencer</h2><p className="text-xs text-neutral-500">Vencidas o con vencimiento en los próximos 7 días.</p><div className="mt-3 space-y-2">{data.quotations.map(item => <Link href={`/dashboard/gestion-comercial/cotizaciones?cotizacion=${item.id}`} className="block rounded-md border border-line p-3 text-sm hover:border-apex" key={item.id}><div className="flex justify-between gap-2"><strong>{item.quotation_number}</strong><span>{shortDate(item.valid_until)}</span></div><p>{item.customer.legal_name} · {item.advisor.name}</p></Link>)}{!data.quotations.length && <p className="py-4 text-sm text-neutral-500">Sin cotizaciones próximas a vencer.</p>}</div></div></div></section></>}
  </div>;
}
