const test = require("node:test");
const assert = require("node:assert/strict");
const { randomUUID } = require("node:crypto");
const { PrismaClient } = require("@prisma/client");

// Opt-in local database integration. All fixtures and writes are rolled back.
test("cotizacion, cancelacion con motivo, pedido, visita y 360 en base local", { skip: process.env.COMMERCIAL_LOCAL_INTEGRATION !== "1" }, async () => {
  const url = new URL(process.env.DATABASE_URL);
  assert.ok(["127.0.0.1", "localhost"].includes(url.hostname), "Solo base local");
  const db = new PrismaClient();
  const corePath = require.resolve("../src/core/prisma");
  const servicePath = require.resolve("../src/modules/commercial-management/service");
  const previous = require.cache[corePath];
  const rollback = new Error("ROLLBACK_FIXTURES");
  try {
    await assert.rejects(db.$transaction(async tx => {
      const adapter = new Proxy(tx, { get(target, key) {
        if (key === "runWithTenant") return (_tenant, fn) => fn();
        if (key === "$transaction") return fn => fn(tx);
        return target[key];
      } });
      require.cache[corePath] = { id: corePath, filename: corePath, loaded: true, exports: adapter };
      delete require.cache[servicePath];
      const service = require(servicePath);
      const tenant = "test-commercial-" + randomUUID();
      const actor = { role: { name: "admin" } };
      const advisor = await tx.commercialAdvisor.create({ data: { tenant_id: tenant, code: "A", name: "QA advisor", user_id: 77801 } });
      const customer = await tx.commercialCustomer.create({ data: { tenant_id: tenant, code: "C", legal_name: "QA customer", advisor_id: advisor.id } });
      const product = await tx.commercialProduct.create({ data: { tenant_id: tenant, code: "P", name: "QA product", unit_price: 100 } });
      const visit = await tx.commercialVisit.create({ data: { tenant_id: tenant, customer_id: customer.id, advisor_id: advisor.id, visit_date: new Date(), status: "IN_PROGRESS", started_at: new Date() } });
      const reason = await tx.commercialVisitReason.create({ data: { tenant_id: tenant, code: "PROSPECT", name: "Prospeccion" } });
      const category = await tx.commercialCustomerCategory.create({ data: { tenant_id: tenant, code: "C", name: "Categoria QA" } });
      const result = await tx.commercialVisitResult.create({ data: { tenant_id: tenant, code: "NONE", name: "Sin venta", requires_observation: false } });
      const prospect = await service.createVisit(tenant, actor, { advisor_id: advisor.id, reason_id: reason.id, visit_date: "2040-01-01T09:00:00-05:00" });
      assert.equal(prospect.customer_id, null);
      await assert.rejects(service.createVisitCustomer(tenant, actor, prospect.id, { code: "NEW", legal_name: "Nuevo", category_id: category.id }), { statusCode: 409 });
      const second = await service.rescheduleVisit(tenant, actor, prospect.id, { visit_date: "2040-02-01T09:00:00-05:00", reason: "Primera reprogramacion" });
      const third = await service.rescheduleVisit(tenant, actor, second.id, { visit_date: "2040-03-01T09:00:00-05:00", reason: "Segunda reprogramacion" });
      assert.equal(third.rescheduled_from_id, second.id);
      const timeline = await service.visitTimeline(tenant, actor, third.id);
      assert.equal(timeline.filter(e => e.event_type === "RESCHEDULED").length, 2);
      assert.ok(timeline.some(e => e.visit_id === prospect.id));
      assert.deepEqual((await service.visitTimeline(tenant, actor, prospect.id)).map(e => e.id), timeline.map(e => e.id));
      await assert.rejects(service.visitTimeline("other-tenant", actor, third.id), { statusCode: 404 });
      await service.startVisit(tenant, actor, third.id);
      await assert.rejects(service.createOrder(tenant, actor, { visit_id: third.id, lines: [{ product_id: product.id, quantity: 1 }] }), { statusCode: 400 });
      await assert.rejects(service.createQuotation(tenant, actor, { visit_id: third.id, lines: [{ product_id: product.id, quantity: 1 }] }), { statusCode: 400 });
      await assert.rejects(service.createOrder(tenant, actor, { customer_id: customer.id, visit_id: third.id, lines: [{ product_id: product.id, quantity: 1 }] }), { statusCode: 400 });
      const linked = await service.createVisitCustomer(tenant, actor, third.id, { code: "NEW", legal_name: "Nuevo", category_id: category.id });
      assert.equal(linked.advisor_id, advisor.id);
      await assert.rejects(service.createVisitCustomer(tenant, actor, third.id, { code: "DUP", legal_name: "Duplicado", category_id: category.id }), { statusCode: 409 });
      assert.equal((await tx.commercialVisit.findUnique({ where: { id: third.id } })).customer_id, linked.id);
      const linkedQuote = await service.createQuotation(tenant, actor, { customer_id: linked.id, visit_id: third.id, lines: [{ product_id: product.id, quantity: 1 }] });
      await service.cancelQuotation(tenant, actor, linkedQuote.id, "Cierre de prueba");
      const noCustomer = await service.createVisit(tenant, actor, { advisor_id: advisor.id, reason_id: reason.id, visit_date: "2040-04-01T09:00:00-05:00" });
      await service.startVisit(tenant, actor, noCustomer.id);
      const completed = await service.completeVisit(tenant, actor, noCustomer.id, { result_id: result.id });
      assert.equal(completed.status, "COMPLETED");
      assert.equal(completed.customer_id, null);
      const input = { customer_id: customer.id, visit_id: visit.id, notes: "Original", lines: [{ product_id: product.id, quantity: 2 }] };
      const quote = await service.createQuotation(tenant, actor, input);
      const cancellable = await service.createQuotation(tenant, actor, input);
      await assert.rejects(service.cancelQuotation(tenant, actor, cancellable.id, "  "), { statusCode: 400 });
      await assert.rejects(service.cancelQuotation("other-tenant", actor, cancellable.id, "No"), { statusCode: 404 });
      const otherAdvisor = await tx.commercialAdvisor.create({ data: { tenant_id: tenant, code: "B", name: "Other", user_id: 77802 } });
      await assert.rejects(service.cancelQuotation(tenant, { id: otherAdvisor.user_id, role: { name: "asesor" } }, cancellable.id, "No"), { statusCode: 404 });
      const cancelled = await service.cancelQuotation(tenant, actor, cancellable.id, "Cliente desistio");
      assert.match(cancelled.notes, /Original\nMotivo de cancelacion: Cliente desistio/);
      const audit = await tx.auditLog.findFirst({ where: { tenant_id: tenant, action: "CANCEL", entity_id: String(cancellable.id) } });
      assert.equal(audit.new_value.cancellation_reason, "Cliente desistio");
      await assert.rejects(service.convertQuotationToOrder(tenant, actor, cancellable.id), { statusCode: 409 });
      const order = await service.convertQuotationToOrder(tenant, actor, quote.id);
      const commitment = await tx.commercialCustomerCommitment.create({ data: { tenant_id: tenant, customer_id: customer.id, advisor_id: advisor.id, visit_id: visit.id, description: 'Enviar ficha tecnica', due_date: new Date('2040-05-01') } });
      const history = await service.visitTimeline(tenant, actor, visit.id, true);
      assert.equal(history.orders[0].id, order.id);
      assert.ok(history.quotations.some(row => row.id === quote.id));
      assert.equal(history.commitments[0].id, commitment.id);
      const chainHistory = await service.visitTimeline(tenant, actor, prospect.id, true);
      assert.deepEqual(new Set(chainHistory.visits.map(row => row.id)), new Set([prospect.id, second.id, third.id]));
      assert.equal(chainHistory.quotations[0].id, linkedQuote.id);
      assert.equal(chainHistory.commitments.length, 0, 'No mezcla compromisos de otras visitas');
      await assert.rejects(service.visitTimeline('other-tenant', actor, visit.id, true), { statusCode: 404 });
      await assert.rejects(service.visitTimeline(tenant, { id: otherAdvisor.user_id, role: { name: 'asesor' } }, visit.id, true), { statusCode: 404 });
      assert.equal(order.quotation_id, quote.id);
      assert.equal(order.visit_id, visit.id);
      assert.equal(order.status, "REGISTERED");
      assert.equal(Number(order.total), 200);
      await assert.rejects(service.convertQuotationToOrder(tenant, actor, quote.id), { statusCode: 409 });
      await assert.rejects(service.cancelQuotation(tenant, actor, quote.id, "No"), { statusCode: 409 });
      assert.equal((await service.listQuotations(tenant, actor, { without_order: "true" })).length, 0);
      const overview = await service.customerOverview(tenant, actor, customer.id);
      assert.equal(overview.customer.last_purchase_at.getTime(), order.order_date.getTime());
      assert.equal(overview.customer.orders[0].id, order.id);
      assert.equal(overview.suggested_products[0].product_id, product.id);
      assert.equal(overview.metrics.sales, 0, "Un registrado no es venta reconocida");
      assert.ok((await service.listCustomers(tenant, actor)).find(row => row.id === customer.id).last_purchase_at);
      const activity = (await service.listVisits(tenant, actor))[0];
      assert.equal(activity.orders[0].id, order.id);
      assert.equal(activity.quotations.length, 2);
      await service.changeOrderStatus(tenant, actor, order.id, "CANCELLED");
      const after = await service.customerOverview(tenant, actor, customer.id);
      assert.equal(after.customer.last_purchase_at, null);
      assert.equal(after.suggested_products.length, 0);
      const report = await service.advisorReport(tenant, actor, { year: 2040, group: 'month' });
      assert.equal(report.totals.total, 2, 'No cuenta programaciones reemplazadas');
      assert.equal(report.totals.completed, 1);
      assert.equal(report.totals.without_result, 1);
      assert.equal((await service.advisorReport('other-tenant', actor, { year: 2040 })).totals.total, 0);
      assert.equal((await service.advisorReport(tenant, { id: otherAdvisor.user_id, role: { name: 'asesor' } }, { year: 2040, advisor_id: advisor.id })).totals.total, 0, 'Filtro no amplía alcance del asesor');
      const extraProduct = await tx.commercialProduct.create({ data: { tenant_id: tenant, code: 'EXTRA', name: 'Extra', unit_price: 50 } });
      const editableQuote = await service.createQuotation(tenant, actor, input);
      const originalLines = JSON.stringify((await service.getQuotation(tenant, actor, editableQuote.id)).lines);
      const editedOrder = await service.convertQuotationToOrder(tenant, actor, editableQuote.id, { lines: [{ product_id: product.id, quantity: 1 }, { product_id: extraProduct.id, quantity: 3 }] });
      assert.equal(editedOrder.quotation_id, editableQuote.id);
      assert.equal(Number(editedOrder.total), 250);
      assert.equal(Number(editedOrder.lines.find(line => line.product_id === product.id).quantity), 1);
      const comparison = await service.quotationComparisonReport(tenant, actor, new Date(editableQuote.quotation_date.getTime() - 5 * 3600000).getUTCFullYear());
      const comparisonRows = comparison.filter(row => row.quotation_id === editableQuote.id);
      assert.equal(comparisonRows.length, 2);
      assert.equal(comparisonRows.find(row => row.product_id === product.id).outcome, 'LESS');
      assert.equal(comparisonRows.find(row => row.product_id === extraProduct.id).outcome, 'ADDED');
      assert.equal(comparisonRows.reduce((sum, row) => sum + row.ordered_value, 0), 250);
      assert.equal((await service.quotationComparisonReport('other-tenant', actor, new Date().getFullYear())).length, 0);
      assert.equal((await service.quotationComparisonReport(tenant, { id: otherAdvisor.user_id, role: { name: 'asesor' } }, new Date().getFullYear())).length, 0);
      assert.equal((await service.quotationComparisonReport(tenant, actor, 2001)).length, 0);
      assert.equal(JSON.stringify((await service.getQuotation(tenant, actor, editableQuote.id)).lines), originalLines, 'La cotizacion original permanece intacta');
      await assert.rejects(service.convertQuotationToOrder(tenant, actor, editableQuote.id, { lines: [{ product_id: product.id, quantity: 4 }] }), { statusCode: 409 });
      assert.ok((await service.listCommitments(tenant, actor, { status: 'PENDING' })).some(item => item.id === commitment.id));
      await assert.rejects(service.changeCommitmentStatus('other-tenant', actor, commitment.id, 'COMPLETED'), { statusCode: 404 });
      await assert.rejects(service.changeCommitmentStatus(tenant, { id: otherAdvisor.user_id, role: { name: 'asesor' } }, commitment.id, 'COMPLETED'), { statusCode: 404 });
      const fulfilled = await service.changeCommitmentStatus(tenant, { id: advisor.user_id, role: { name: 'asesor' } }, commitment.id, 'COMPLETED');
      assert.equal(fulfilled.status, 'COMPLETED');
      assert.ok(fulfilled.completed_at);
      assert.ok(!(await service.listCommitments(tenant, actor, { status: 'PENDING' })).some(item => item.id === commitment.id));
      assert.ok((await service.listCommitments(tenant, actor, { status: 'COMPLETED' })).some(item => item.id === commitment.id));
      assert.ok(await tx.auditLog.findFirst({ where: { tenant_id: tenant, entity: 'CommercialCustomerCommitment', entity_id: String(commitment.id), action: 'STATUS_CHANGE' } }));
      await assert.rejects(service.changeCommitmentStatus('other-tenant', actor, commitment.id, 'PENDING'), { statusCode: 404 });
      await assert.rejects(service.changeCommitmentStatus(tenant, { id: otherAdvisor.user_id, role: { name: 'asesor' } }, commitment.id, 'PENDING'), { statusCode: 404 });
      const reopened = await service.changeCommitmentStatus(tenant, { id: advisor.user_id, role: { name: 'asesor' } }, commitment.id, 'PENDING');
      assert.equal(reopened.status, 'PENDING');
      assert.equal(reopened.completed_at, null);
      assert.equal(reopened.due_date.getTime(), commitment.due_date.getTime());
      assert.ok((await service.listCommitments(tenant, actor, { status: 'PENDING' })).some(item => item.id === commitment.id));
      assert.ok(!(await service.listCommitments(tenant, actor, { status: 'COMPLETED' })).some(item => item.id === commitment.id));
      assert.equal(await tx.auditLog.count({ where: { tenant_id: tenant, entity: 'CommercialCustomerCommitment', entity_id: String(commitment.id), action: 'STATUS_CHANGE' } }), 2);
      throw rollback;
    }, { timeout: 30000 }), error => error === rollback);
  } finally {
    if (previous) require.cache[corePath] = previous; else delete require.cache[corePath];
    delete require.cache[servicePath];
    await db.$disconnect();
  }
});
