const test=require('node:test'),assert=require('node:assert/strict');
const {pack,overlaps,inside}=require('../src/modules/transport/packing-engine');
const {settlementLines,remainingDeliveryLines,validatePodInput}=require('../src/modules/transport/tms-service');
const container={length:6,width:2.4,height:2.4,max_weight:8000};
const item={id:'a',quantity:24,length:0.6,width:0.4,height:0.4,weight:50,rotation:'upright',stackable:true,max_top_load:150,stop:1};
function invariant(plan){let weight=0;const ids=new Set();for(const b of plan.placements){assert.ok(inside(b,{...plan.container,x:0,y:0,z:0}));assert.ok(!ids.has(b.unit_id));ids.add(b.unit_id);weight+=b.weight;assert.ok(b.load_above<=b.max_top_load+1e-6);for(const o of plan.container.obstacles)assert.ok(!overlaps(b,o));const space=plan.container.spaces.find(s=>s.id===b.space_id);assert.ok(inside(b,space));if(b.z>space.z+1e-6){const support=plan.placements.find(p=>p.unit_id===b.support_id);assert.ok(support?.stackable);assert.ok(Math.abs(support.z+support.height-b.z)<1e-6);assert.ok(b.x>=support.x-1e-6&&b.x+b.length<=support.x+support.length+1e-6&&b.y>=support.y-1e-6&&b.y+b.width<=support.y+support.width+1e-6);}}for(let i=0;i<plan.placements.length;i++)for(let j=0;j<i;j++)assert.ok(!overlaps(plan.placements[i],plan.placements[j]));assert.ok(weight<=plan.container.max_weight);assert.equal(plan.placements.length+plan.unplaced.length,plan.requested_units);}
test('24 real cartons fit with invariant checks and deterministic coordinates',()=>{const input={container,items:[item]},a=pack(input),b=pack(input);assert.equal(a.feasible,true);assert.deepEqual(a.placements,b.placements);invariant(a);});
test('weight, oversized, rotation and non-stackable constraints',()=>{assert.equal(pack({container:{...container,max_weight:40},items:[{...item,quantity:1}]}).placements.length,0);assert.equal(pack({container,items:[{...item,quantity:1,length:7,rotation:'none'}]}).feasible,false);const c={length:1,width:2,height:1,max_weight:100};assert.equal(pack({container:c,items:[{...item,quantity:1,length:2,width:1,height:1,rotation:'none'}]}).feasible,false);assert.equal(pack({container:c,items:[{...item,quantity:1,length:2,width:1,height:1,rotation:'upright'}]}).feasible,true);const p=pack({container:{length:1,width:1,height:3,max_weight:1000},items:[{...item,quantity:2,length:1,width:1,height:1,stackable:false}]});assert.equal(p.placements.length,1);invariant(p);});
test('support load is propagated to every ancestor',()=>{const p=pack({container:{length:1,width:1,height:5,max_weight:1000},items:[{...item,quantity:5,length:1,width:1,height:1,weight:10,max_top_load:15}]});assert.equal(p.placements.length,2);invariant(p);});
test('compartments, temperature and obstacles are enforced',()=>{const c={length:4,width:2,height:2,max_weight:1000,spaces:[{id:'cold',x:0,y:0,z:0,length:2,width:2,height:2,temperature_min:0,temperature_max:5,groups:['food']},{id:'dry',x:2,y:0,z:0,length:2,width:2,height:2,groups:['dry']}],obstacles:[{x:0,y:0,z:0,length:1,width:1,height:2}]};const p=pack({container:c,items:[{...item,quantity:6,group:'food',temperature:3}]});assert.ok(p.placements.every(b=>b.space_id==='cold'));invariant(p);assert.equal(pack({container:c,items:[{...item,quantity:1,temperature:-20}]}).feasible,false);});
test('malformed and excessive input fails closed',()=>{for(const bad of [{...item,quantity:251},{...item,quantity:1.5},{...item,length:0},{...item,weight:Infinity}])assert.throws(()=>pack({container,items:[bad]}));assert.throws(()=>pack({container:{...container,spaces:[{id:'bad',x:20,y:0,z:0,length:2,width:2,height:2}]},items:[item]}));});
test('100 seeded mixed-load scenarios preserve physical invariants',()=>{let seed=17;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/2**32;};for(let i=0;i<100;i++){const items=Array.from({length:4},(_,j)=>({...item,id:String(j),quantity:4,length:0.2+random()*1.5,width:0.2+random(),height:0.2+random(),weight:1+random()*100,max_top_load:50+random()*300,rotation:j%2?'free':'upright',stop:j+1}));invariant(pack({container,items}));}});
test('financial lines reject negative, forged and nonfinite totals',()=>{assert.throws(()=>settlementLines([{concept:'F',quantity:2,unit_rate:100,total:-999}]));assert.throws(()=>settlementLines([{concept:'F',quantity:-1,unit_rate:100}]));assert.throws(()=>settlementLines([{concept:'F',quantity:1,unit_rate:Infinity}]));assert.equal(settlementLines([{concept:'F',quantity:3,unit_rate:0.1}])[0].total,0.3);});
test('partial deliveries preserve remaining quantities and reject duplicate SKU',()=>{assert.equal(remainingDeliveryLines([{sku:'A',quantity:5}],[{delivered_lines:[{sku:'A',quantity:2}]}])[0].quantity,3);assert.throws(()=>validatePodInput({result:'parcial',delivered_lines:[{sku:'A',quantity:4},{sku:'A',quantity:4}],pod:{receiver_name:'A',photos:['tms-evidence/t/photo.png'],signature:'tms-evidence/t/sign.png'}},{lines:[{sku:'A',quantity:5}]}),e=>e.code==='TMS_DUPLICATE_SKU');});
