-- HR operational traceability for Marcaciones.
-- Non-destructive: keeps TimePunch and preoperational checklist flow intact.

create table if not exists public."WorkSession" (
  id integer generated by default as identity primary key,
  tenant_id text not null,
  employee_id integer,
  user_name text not null,
  date timestamptz not null,
  status text not null default 'activa',
  started_at timestamptz not null default now(),
  lunch_started_at timestamptz,
  lunch_ended_at timestamptz,
  closed_at timestamptz,
  entry_punch_id integer,
  exit_punch_id integer,
  route_id integer,
  vehicle_plate text,
  preop_checklist_id integer,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public."ActivityType" (
  id integer generated by default as identity primary key,
  tenant_id text not null,
  name text not null,
  description text,
  active boolean not null default true,
  sort_order integer not null default 100,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint "ActivityType_tenant_name_unique" unique (tenant_id, name)
);

create table if not exists public."WorkActivity" (
  id integer generated by default as identity primary key,
  tenant_id text not null,
  session_id integer not null references public."WorkSession"(id) on delete cascade,
  activity_type_id integer references public."ActivityType"(id),
  activity_type_name text not null,
  employee_id integer,
  user_name text not null,
  route_id integer,
  vehicle_plate text,
  occurred_at timestamptz not null default now(),
  latitude double precision not null,
  longitude double precision not null,
  accuracy_meters double precision,
  approximate_address text,
  observation text not null,
  status text not null default 'registrada',
  alert_level text not null default 'normal',
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists public."ActivityEvidence" (
  id integer generated by default as identity primary key,
  tenant_id text not null,
  activity_id integer not null references public."WorkActivity"(id) on delete cascade,
  evidence_type text not null default 'photo',
  file_name text not null,
  file_url text,
  storage_path text,
  base64_data text,
  mime_type text,
  file_size integer,
  uploaded_by integer,
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'
);

create index if not exists "WorkSession_tenant_employee_date_idx" on public."WorkSession"(tenant_id, employee_id, date);
create index if not exists "WorkSession_tenant_user_date_idx" on public."WorkSession"(tenant_id, user_name, date);
create index if not exists "WorkSession_tenant_status_idx" on public."WorkSession"(tenant_id, status);
create index if not exists "ActivityType_tenant_active_idx" on public."ActivityType"(tenant_id, active, sort_order);
create index if not exists "WorkActivity_tenant_session_idx" on public."WorkActivity"(tenant_id, session_id, occurred_at);
create index if not exists "WorkActivity_tenant_employee_idx" on public."WorkActivity"(tenant_id, employee_id, occurred_at);
create index if not exists "WorkActivity_tenant_route_idx" on public."WorkActivity"(tenant_id, route_id, occurred_at);
create index if not exists "ActivityEvidence_tenant_activity_idx" on public."ActivityEvidence"(tenant_id, activity_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('operational-evidence', 'operational-evidence', false, 10485760, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
