-- Apex Heart is tenant-facing and restricted to company owners/admins.
create table if not exists public.apex_heart_configs (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  annual_financing_rate numeric(8,4) not null default 14.42,
  lost_portfolio_rate numeric(8,4) not null default 5,
  holding_rate numeric(8,4) not null default 25,
  order_cost numeric(18,2) not null default 50000,
  lead_time_days integer not null default 14,
  safety_stock_days integer not null default 1,
  inventory_target_days integer not null default 60,
  alert_email_enabled boolean not null default true,
  alert_in_app_enabled boolean not null default true,
  recipients jsonb not null default '["owner","admin"]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(company_id)
);

create table if not exists public.apex_heart_alert_rules (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  code text not null,
  name text not null,
  description text,
  metric text not null,
  operator text not null check (operator in ('gt','lt')),
  warning_threshold numeric not null,
  critical_threshold numeric not null,
  severity text not null default 'warning',
  enabled boolean not null default true,
  cooldown_hours integer not null default 24 check (cooldown_hours between 1 and 720),
  action_label text,
  action_href text,
  recipients jsonb not null default '["owner","admin"]'::jsonb,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(company_id, code)
);

create table if not exists public.apex_heart_alerts (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  rule_id bigint references public.apex_heart_alert_rules(id) on delete set null,
  fingerprint text not null,
  metric text not null,
  metric_value numeric not null,
  threshold numeric not null,
  severity text not null check (severity in ('warning','critical')),
  status text not null default 'open' check (status in ('open','acknowledged','resolved')),
  title text not null,
  message text not null,
  action_label text,
  action_href text,
  context jsonb not null default '{}'::jsonb,
  detected_at timestamptz not null default now(),
  acknowledged_at timestamptz,
  acknowledged_by uuid references auth.users(id),
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(company_id, fingerprint)
);

create table if not exists public.apex_heart_inventory_snapshots (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  snapshot_date date not null,
  item_id text not null,
  quantity numeric not null default 0,
  unit_cost numeric not null default 0,
  value numeric not null default 0,
  source text not null default 'system',
  created_at timestamptz not null default now(),
  unique(company_id, snapshot_date, item_id)
);

create index if not exists apex_heart_rules_company_enabled_idx on public.apex_heart_alert_rules(company_id, enabled);
create index if not exists apex_heart_alerts_company_status_idx on public.apex_heart_alerts(company_id, status, severity);
create index if not exists apex_heart_snapshots_company_date_idx on public.apex_heart_inventory_snapshots(company_id, snapshot_date);

alter table public.apex_heart_configs enable row level security;
alter table public.apex_heart_alert_rules enable row level security;
alter table public.apex_heart_alerts enable row level security;
alter table public.apex_heart_inventory_snapshots enable row level security;

create policy apex_heart_configs_admin_all on public.apex_heart_configs for all to authenticated
using (app_private.is_company_admin(company_id)) with check (app_private.is_company_admin(company_id));
create policy apex_heart_rules_admin_all on public.apex_heart_alert_rules for all to authenticated
using (app_private.is_company_admin(company_id)) with check (app_private.is_company_admin(company_id));
create policy apex_heart_alerts_admin_all on public.apex_heart_alerts for all to authenticated
using (app_private.is_company_admin(company_id)) with check (app_private.is_company_admin(company_id));
create policy apex_heart_snapshots_admin_read on public.apex_heart_inventory_snapshots for select to authenticated
using (app_private.is_company_admin(company_id));

revoke all on public.apex_heart_configs, public.apex_heart_alert_rules, public.apex_heart_alerts, public.apex_heart_inventory_snapshots from anon;
grant select, insert, update on public.apex_heart_configs, public.apex_heart_alert_rules, public.apex_heart_alerts to authenticated;
grant select on public.apex_heart_inventory_snapshots to authenticated;
grant all on public.apex_heart_configs, public.apex_heart_alert_rules, public.apex_heart_alerts, public.apex_heart_inventory_snapshots to service_role;

insert into public.modules (code, name, description, route, icon, is_active, sort_order, visibility_scope)
values ('apex_heart', 'Apex Heart', 'Control gerencial transversal de productividad, margen, inventario, compras, ventas, cartera y caja.', '/dashboard/reportes/apex-heart', 'heart-pulse', true, 20, 'tenant')
on conflict (code) do update set name=excluded.name, description=excluded.description, route=excluded.route, icon=excluded.icon, is_active=true, sort_order=excluded.sort_order;

insert into public.plan_modules (plan_id, module_id, enabled)
select p.id, m.id, true from public.plans p join public.modules m on m.code='apex_heart'
on conflict (plan_id, module_id) do update set enabled=true;

insert into public.company_modules (company_id, module_id, enabled, source)
select c.id, m.id, true, 'plan' from public.companies c join public.modules m on m.code='apex_heart'
on conflict (company_id, module_id) do update set enabled=true;
