-- Vehicle and transport rate master catalogs (ficha + tarifarios).
-- Non destructive: seeds global master_catalogs/master_catalog_items entries
-- (on conflict do nothing) so every tenant starts with selectable lists that
-- can be extended per company from Administracion > Catalogos maestros.

with catalogs(code, name, description, scope, sort_order) as (
  values
    ('vehicle_categories', 'Categorias vehiculares', 'Clasificacion de peso/tipo de servicio del vehiculo.', 'mixed', 110),
    ('vehicle_brands', 'Marcas de vehiculo', 'Marcas registradas para la flota.', 'mixed', 120),
    ('vehicle_lines', 'Lineas de vehiculo', 'Lineas o referencias por marca (parent_code = marca).', 'mixed', 130),
    ('vehicle_colors', 'Colores de vehiculo', 'Colores habituales de la flota.', 'mixed', 140),
    ('vehicle_fuels', 'Combustibles', 'Tipos de combustible/alimentacion.', 'mixed', 150),
    ('vehicle_body_types', 'Carrocerias', 'Tipos de carroceria.', 'mixed', 160),
    ('service_levels', 'Niveles de servicio', 'Niveles de servicio de transporte para tarifarios y despachos.', 'mixed', 170),
    ('departments', 'Departamentos', 'Departamentos de Colombia para el alcance de tarifarios y rutas.', 'mixed', 180),
    ('cities', 'Ciudades', 'Ciudades de Colombia por departamento (parent_code = departamento).', 'mixed', 190),
    ('currencies', 'Monedas', 'Monedas para tarifarios y costos de transporte.', 'mixed', 200),
    ('municipalities', 'Municipios', 'Municipios de Colombia por ciudad (parent_code = ciudad).', 'mixed', 210)
)
insert into public.master_catalogs (code, name, description, scope, sort_order)
select code, name, description, scope, sort_order
from catalogs
on conflict do nothing;

with catalog_items(catalog_code, code, name, sort_order) as (
  values
    ('vehicle_types', 'motocicleta', 'Motocicleta', 40),
    ('vehicle_types', 'automovil', 'Automovil', 50),
    ('vehicle_types', 'buseta', 'Buseta', 60),
    ('vehicle_types', 'bus', 'Bus', 70),
    ('vehicle_types', 'camion_tracto', 'Camion tracto', 80),
    ('vehicle_types', 'volqueta', 'Volqueta', 90),
    ('vehicle_categories', 'motocicleta', 'Motocicleta', 10),
    ('vehicle_categories', 'liviano', 'Liviano', 20),
    ('vehicle_categories', 'utilitario', 'Utilitario', 30),
    ('vehicle_categories', 'camion_liviano', 'Camion liviano', 40),
    ('vehicle_categories', 'camion_mediano', 'Camion mediano', 50),
    ('vehicle_categories', 'camion_pesado', 'Camion pesado', 60),
    ('vehicle_categories', 'articulado', 'Articulado / tractomula', 70),
    ('vehicle_brands', 'toyota', 'Toyota', 10),
    ('vehicle_brands', 'chevrolet', 'Chevrolet', 20),
    ('vehicle_brands', 'renault', 'Renault', 30),
    ('vehicle_brands', 'nissan', 'Nissan', 40),
    ('vehicle_brands', 'mazda', 'Mazda', 50),
    ('vehicle_brands', 'ford', 'Ford', 60),
    ('vehicle_brands', 'volkswagen', 'Volkswagen', 70),
    ('vehicle_brands', 'mercedes_benz', 'Mercedes-Benz', 80),
    ('vehicle_brands', 'hyundai', 'Hyundai', 90),
    ('vehicle_brands', 'kia', 'Kia', 100),
    ('vehicle_brands', 'iveco', 'Iveco', 110),
    ('vehicle_brands', 'hino', 'Hino', 120),
    ('vehicle_colors', 'blanco', 'Blanco', 10),
    ('vehicle_colors', 'negro', 'Negro', 20),
    ('vehicle_colors', 'gris', 'Gris', 30),
    ('vehicle_colors', 'plata', 'Plata', 40),
    ('vehicle_colors', 'rojo', 'Rojo', 50),
    ('vehicle_colors', 'azul', 'Azul', 60),
    ('vehicle_colors', 'verde', 'Verde', 70),
    ('vehicle_colors', 'amarillo', 'Amarillo', 80),
    ('vehicle_colors', 'naranja', 'Naranja', 90),
    ('vehicle_colors', 'beige', 'Beige', 100),
    ('vehicle_colors', 'cafe', 'Cafe', 110),
    ('vehicle_colors', 'vinotinto', 'Vinotinto', 120),
    ('vehicle_fuels', 'gasolina', 'Gasolina', 10),
    ('vehicle_fuels', 'diesel', 'Diesel', 20),
    ('vehicle_fuels', 'gnv', 'Gas natural (GNV)', 30),
    ('vehicle_fuels', 'gnv_gasolina', 'Gasolina + GNV', 40),
    ('vehicle_fuels', 'electrico', 'Electrico', 50),
    ('vehicle_fuels', 'hibrido', 'Hibrido', 60),
    ('vehicle_body_types', 'estacas', 'Estacas', 10),
    ('vehicle_body_types', 'caja_seca', 'Caja seca', 20),
    ('vehicle_body_types', 'furgon', 'Furgon', 30),
    ('vehicle_body_types', 'plataforma', 'Plataforma', 40),
    ('vehicle_body_types', 'tanque', 'Tanque', 50),
    ('vehicle_body_types', 'volco', 'Volco', 60),
    ('vehicle_body_types', 'refrigerado', 'Refrigerado', 70),
    ('vehicle_body_types', 'porta_contenedores', 'Porta contenedores', 80),
    ('vehicle_body_types', 'cama_baja', 'Cama baja', 90),
    ('units_of_measure', 'TON', 'Tonelada', 40),
    ('units_of_measure', 'M3', 'Metro cubico', 50),
    ('units_of_measure', 'LB', 'Libra', 60),
    ('service_levels', 'normal', 'Normal', 10),
    ('service_levels', 'express', 'Express', 20),
    ('service_levels', 'programado', 'Programado', 30),
    ('service_levels', 'dedicado', 'Dedicado', 40),
    ('departments', 'amazonas', 'Amazonas', 10),
    ('departments', 'antioquia', 'Antioquia', 20),
    ('departments', 'arauca', 'Arauca', 30),
    ('departments', 'atlantico', 'Atlantico', 40),
    ('departments', 'bogota_dc', 'Bogota D.C.', 50),
    ('departments', 'bolivar', 'Bolivar', 60),
    ('departments', 'boyaca', 'Boyaca', 70),
    ('departments', 'caldas', 'Caldas', 80),
    ('departments', 'caqueta', 'Caqueta', 90),
    ('departments', 'casanare', 'Casanare', 100),
    ('departments', 'cauca', 'Cauca', 110),
    ('departments', 'cesar', 'Cesar', 120),
    ('departments', 'choco', 'Choco', 130),
    ('departments', 'cordoba', 'Cordoba', 140),
    ('departments', 'cundinamarca', 'Cundinamarca', 150),
    ('departments', 'guainia', 'Guainia', 160),
    ('departments', 'guaviare', 'Guaviare', 170),
    ('departments', 'huila', 'Huila', 180),
    ('departments', 'la_guajira', 'La Guajira', 190),
    ('departments', 'magdalena', 'Magdalena', 200),
    ('departments', 'meta', 'Meta', 210),
    ('departments', 'narino', 'Narino', 220),
    ('departments', 'norte_de_santander', 'Norte de Santander', 230),
    ('departments', 'putumayo', 'Putumayo', 240),
    ('departments', 'quindio', 'Quindio', 250),
    ('departments', 'risaralda', 'Risaralda', 260),
    ('departments', 'san_andres', 'San Andres y Providencia', 270),
    ('departments', 'santander', 'Santander', 280),
    ('departments', 'sucre', 'Sucre', 290),
    ('departments', 'tolima', 'Tolima', 300),
    ('departments', 'valle_del_cauca', 'Valle del Cauca', 310),
    ('departments', 'vaupes', 'Vaupes', 320),
    ('departments', 'vichada', 'Vichada', 330),
    ('currencies', 'COP', 'Peso colombiano (COP)', 10),
    ('currencies', 'USD', 'Dolar estadounidense (USD)', 20),
    ('currencies', 'EUR', 'Euro (EUR)', 30)
)
insert into public.master_catalog_items (catalog_id, code, name, sort_order)
select c.id, i.code, i.name, i.sort_order
from catalog_items i
join public.master_catalogs c on c.code = i.catalog_code and c.company_id is null
on conflict do nothing;

with line_items(code, name, sort_order, parent_code) as (
  values
    ('hilux', 'Hilux', 10, 'toyota'),
    ('fortuner', 'Fortuner', 20, 'toyota'),
    ('nhr', 'NHR', 10, 'chevrolet'),
    ('npr', 'NPR', 20, 'chevrolet'),
    ('dmax', 'D-Max', 30, 'chevrolet'),
    ('spark_gt', 'Spark GT', 40, 'chevrolet'),
    ('kangoo', 'Kangoo', 10, 'renault'),
    ('trafic', 'Trafic', 20, 'renault'),
    ('logan', 'Logan', 30, 'renault'),
    ('frontier', 'Frontier', 10, 'nissan'),
    ('urvan', 'Urvan', 20, 'nissan'),
    ('bt50', 'BT-50', 10, 'mazda'),
    ('ranger', 'Ranger', 10, 'ford'),
    ('transit', 'Transit', 20, 'ford'),
    ('amarok', 'Amarok', 10, 'volkswagen'),
    ('delivery', 'Delivery', 20, 'volkswagen'),
    ('sprinter', 'Sprinter', 10, 'mercedes_benz'),
    ('atego', 'Atego', 20, 'mercedes_benz'),
    ('daily', 'Daily', 10, 'iveco'),
    ('dutro', 'Dutro', 10, 'hino')
)
insert into public.master_catalog_items (catalog_id, code, name, sort_order, parent_code)
select c.id, i.code, i.name, i.sort_order, i.parent_code
from line_items i
join public.master_catalogs c on c.code = 'vehicle_lines' and c.company_id is null
on conflict do nothing;

with city_items(code, name, sort_order, parent_code) as (
  values
    ('bogota', 'Bogota', 10, 'bogota_dc'),
    ('medellin', 'Medellin', 20, 'antioquia'),
    ('cali', 'Cali', 30, 'valle_del_cauca'),
    ('barranquilla', 'Barranquilla', 40, 'atlantico'),
    ('cartagena', 'Cartagena', 50, 'bolivar'),
    ('bucaramanga', 'Bucaramanga', 60, 'santander'),
    ('pereira', 'Pereira', 70, 'risaralda'),
    ('manizales', 'Manizales', 80, 'caldas'),
    ('ibague', 'Ibague', 90, 'tolima'),
    ('villavicencio', 'Villavicencio', 100, 'meta'),
    ('cucuta', 'Cucuta', 110, 'norte_de_santander'),
    ('armenia', 'Armenia', 120, 'quindio'),
    ('monteria', 'Monteria', 130, 'cordoba'),
    ('santa_marta', 'Santa Marta', 140, 'magdalena'),
    ('neiva', 'Neiva', 150, 'huila'),
    ('popayan', 'Popayan', 160, 'cauca'),
    ('pasto', 'Pasto', 170, 'narino'),
    ('sincelejo', 'Sincelejo', 180, 'sucre'),
    ('tunja', 'Tunja', 190, 'boyaca'),
    ('florencia', 'Florencia', 200, 'caqueta'),
    ('yopal', 'Yopal', 210, 'casanare'),
    ('riohacha', 'Riohacha', 220, 'la_guajira'),
    ('valledupar', 'Valledupar', 230, 'cesar'),
    ('quibdo', 'Quibdo', 240, 'choco')
)
insert into public.master_catalog_items (catalog_id, code, name, sort_order, parent_code)
select c.id, i.code, i.name, i.sort_order, i.parent_code
from city_items i
join public.master_catalogs c on c.code = 'cities' and c.company_id is null
on conflict do nothing;

with municipality_items(code, name, sort_order, parent_code) as (
  values
    ('bogota', 'Bogota', 10, 'bogota'),
    ('soacha', 'Soacha', 20, 'bogota'),
    ('chia', 'Chia', 30, 'bogota'),
    ('zipaquira', 'Zipaquira', 40, 'bogota'),
    ('mosquera', 'Mosquera', 50, 'bogota'),
    ('funza', 'Funza', 60, 'bogota'),
    ('madrid', 'Madrid', 70, 'bogota'),
    ('facatativa', 'Facatativa', 80, 'bogota'),
    ('fusagasuga', 'Fusagasuga', 90, 'bogota'),
    ('cajica', 'Cajica', 100, 'bogota'),
    ('tabio', 'Tabio', 110, 'bogota'),
    ('tenjo', 'Tenjo', 120, 'bogota'),
    ('medellin', 'Medellin', 10, 'medellin'),
    ('envigado', 'Envigado', 20, 'medellin'),
    ('itagui', 'Itagui', 30, 'medellin'),
    ('bello', 'Bello', 40, 'medellin'),
    ('copacabana', 'Copacabana', 50, 'medellin'),
    ('sabaneta', 'Sabaneta', 60, 'medellin'),
    ('la_estrella', 'La Estrella', 70, 'medellin'),
    ('girardota', 'Girardota', 80, 'medellin'),
    ('barbosa', 'Barbosa', 90, 'medellin'),
    ('rionegro', 'Rionegro', 100, 'medellin'),
    ('cali', 'Cali', 10, 'cali'),
    ('palmira', 'Palmira', 20, 'cali'),
    ('jamundi', 'Jamundi', 30, 'cali'),
    ('yumbo', 'Yumbo', 40, 'cali'),
    ('buga', 'Buga', 50, 'cali'),
    ('tulua', 'Tulua', 60, 'cali'),
    ('cartago', 'Cartago', 70, 'cali'),
    ('florida', 'Florida', 80, 'cali'),
    ('cerrito', 'Cerrito', 90, 'cali'),
    ('barranquilla', 'Barranquilla', 10, 'barranquilla'),
    ('soledad', 'Soledad', 20, 'barranquilla'),
    ('puerto_colombia', 'Puerto Colombia', 30, 'barranquilla'),
    ('malambo', 'Malambo', 40, 'barranquilla'),
    ('galapa', 'Galapa', 50, 'barranquilla'),
    ('sabanalarga', 'Sabanalarga', 60, 'barranquilla'),
    ('cartagena', 'Cartagena', 10, 'cartagena'),
    ('turbaco', 'Turbaco', 20, 'cartagena'),
    ('turbana', 'Turbana', 30, 'cartagena'),
    ('clemencia', 'Clemencia', 40, 'cartagena'),
    ('maria_la_baja', 'Maria La Baja', 50, 'cartagena'),
    ('bucaramanga', 'Bucaramanga', 10, 'bucaramanga'),
    ('floridablanca', 'Floridablanca', 20, 'bucaramanga'),
    ('giron', 'Giron', 30, 'bucaramanga'),
    ('piedecuesta', 'Piedecuesta', 40, 'bucaramanga'),
    ('lebrija', 'Lebrija', 50, 'bucaramanga'),
    ('pereira', 'Pereira', 10, 'pereira'),
    ('dosquebradas', 'Dosquebradas', 20, 'pereira'),
    ('la_virginia', 'La Virginia', 30, 'pereira'),
    ('santa_rosa_de_cabal', 'Santa Rosa de Cabal', 40, 'pereira'),
    ('marsella', 'Marsella', 50, 'pereira'),
    ('apia', 'Apia', 60, 'pereira'),
    ('manizales', 'Manizales', 10, 'manizales'),
    ('villamaria', 'Villamaria', 20, 'manizales'),
    ('neira', 'Neira', 30, 'manizales'),
    ('chinchina', 'Chinchina', 40, 'manizales'),
    ('palestina', 'Palestina', 50, 'manizales'),
    ('la_dorada', 'La Dorada', 60, 'manizales'),
    ('ibague', 'Ibague', 10, 'ibague'),
    ('cajamarca', 'Cajamarca', 20, 'ibague'),
    ('espinal', 'Espinal', 30, 'ibague'),
    ('natagaima', 'Natagaima', 40, 'ibague'),
    ('chaparral', 'Chaparral', 50, 'ibague'),
    ('guamo', 'Guamo', 60, 'ibague'),
    ('villavicencio', 'Villavicencio', 10, 'villavicencio'),
    ('acacias', 'Acacias', 20, 'villavicencio'),
    ('granada', 'Granada', 30, 'villavicencio'),
    ('san_martin', 'San Martin', 40, 'villavicencio'),
    ('restrepo', 'Restrepo', 50, 'villavicencio'),
    ('cucuta', 'Cucuta', 10, 'cucuta'),
    ('los_patios', 'Los Patios', 20, 'cucuta'),
    ('villa_del_rosario', 'Villa del Rosario', 30, 'cucuta'),
    ('el_zulia', 'El Zulia', 40, 'cucuta'),
    ('pamplona', 'Pamplona', 50, 'cucuta'),
    ('ocana', 'Ocana', 60, 'cucuta'),
    ('armenia', 'Armenia', 10, 'armenia'),
    ('calarca', 'Calarca', 20, 'armenia'),
    ('montenegro', 'Montenegro', 30, 'armenia'),
    ('quimbaya', 'Quimbaya', 40, 'armenia'),
    ('la_tebaida', 'La Tebaida', 50, 'armenia'),
    ('salento', 'Salento', 60, 'armenia'),
    ('filandia', 'Filandia', 70, 'armenia'),
    ('cordoba', 'Cordoba', 80, 'armenia'),
    ('monteria', 'Monteria', 10, 'monteria'),
    ('cerete', 'Cerete', 20, 'monteria'),
    ('lorica', 'Lorica', 30, 'monteria'),
    ('san_pelayo', 'San Pelayo', 40, 'monteria'),
    ('canalete', 'Canalete', 50, 'monteria'),
    ('santa_marta', 'Santa Marta', 10, 'santa_marta'),
    ('cienaga', 'Cienaga', 20, 'santa_marta'),
    ('fundacion', 'Fundacion', 30, 'santa_marta'),
    ('aracataca', 'Aracataca', 40, 'santa_marta'),
    ('el_banco', 'El Banco', 50, 'santa_marta'),
    ('neiva', 'Neiva', 10, 'neiva'),
    ('pitalito', 'Pitalito', 20, 'neiva'),
    ('garzon', 'Garzon', 30, 'neiva'),
    ('la_plata', 'La Plata', 40, 'neiva'),
    ('palermo', 'Palermo', 50, 'neiva'),
    ('rivera', 'Rivera', 60, 'neiva'),
    ('popayan', 'Popayan', 10, 'popayan'),
    ('timbio', 'Timbio', 20, 'popayan'),
    ('piendamo', 'Piendamo', 30, 'popayan'),
    ('santander_de_quilichao', 'Santander de Quilichao', 40, 'popayan'),
    ('el_bordo', 'El Bordo', 50, 'popayan'),
    ('pasto', 'Pasto', 10, 'pasto'),
    ('ipiales', 'Ipiales', 20, 'pasto'),
    ('tuquerres', 'Tuquerres', 30, 'pasto'),
    ('consaca', 'Consaca', 40, 'pasto'),
    ('guaitarilla', 'Guaitarilla', 50, 'pasto'),
    ('sincelejo', 'Sincelejo', 10, 'sincelejo'),
    ('corozal', 'Corozal', 20, 'sincelejo'),
    ('sampues', 'Sampues', 30, 'sincelejo'),
    ('los_palmitos', 'Los Palmitos', 40, 'sincelejo'),
    ('magangue', 'Magangue', 50, 'sincelejo'),
    ('toluviejo', 'Toluviejo', 60, 'sincelejo'),
    ('tunja', 'Tunja', 10, 'tunja'),
    ('duitama', 'Duitama', 20, 'tunja'),
    ('sogamoso', 'Sogamoso', 30, 'tunja'),
    ('chiquinquira', 'Chiquinquira', 40, 'tunja'),
    ('moniquira', 'Moniquira', 50, 'tunja'),
    ('villa_de_leyva', 'Villa de Leyva', 60, 'tunja'),
    ('paipa', 'Paipa', 70, 'tunja'),
    ('florencia', 'Florencia', 10, 'florencia'),
    ('morelia', 'Morelia', 20, 'florencia'),
    ('puerto_rico', 'Puerto Rico', 30, 'florencia'),
    ('san_vicente_del_caguan', 'San Vicente del Caguan', 40, 'florencia'),
    ('el_doncello', 'El Doncello', 50, 'florencia'),
    ('belen_de_los_andaquies', 'Belen de los Andaquies', 60, 'florencia'),
    ('yopal', 'Yopal', 10, 'yopal'),
    ('aguazul', 'Aguazul', 20, 'yopal'),
    ('villanueva', 'Villanueva', 30, 'yopal'),
    ('paz_de_ariporo', 'Paz de Ariporo', 40, 'yopal'),
    ('tauramena', 'Tauramena', 50, 'yopal'),
    ('monterrey', 'Monterrey', 60, 'yopal'),
    ('riohacha', 'Riohacha', 10, 'riohacha'),
    ('maicao', 'Maicao', 20, 'riohacha'),
    ('barrancas', 'Barrancas', 30, 'riohacha'),
    ('fonseca', 'Fonseca', 40, 'riohacha'),
    ('san_juan_del_cesar', 'San Juan del Cesar', 50, 'riohacha'),
    ('distraccion', 'Distraccion', 60, 'riohacha'),
    ('albania', 'Albania', 70, 'riohacha'),
    ('valledupar', 'Valledupar', 10, 'valledupar'),
    ('aguachica', 'Aguachica', 20, 'valledupar'),
    ('bosconia', 'Bosconia', 30, 'valledupar'),
    ('chiriguana', 'Chiriguana', 40, 'valledupar'),
    ('la_paz', 'La Paz', 50, 'valledupar'),
    ('pueblo_bello', 'Pueblo Bello', 60, 'valledupar'),
    ('quibdo', 'Quibdo', 10, 'quibdo'),
    ('istmina', 'Istmina', 20, 'quibdo'),
    ('condoto', 'Condoto', 30, 'quibdo'),
    ('nuqui', 'Nuqui', 40, 'quibdo')
)
insert into public.master_catalog_items (catalog_id, code, name, sort_order, parent_code)
select c.id, i.code, i.name, i.sort_order, i.parent_code
from municipality_items i
join public.master_catalogs c on c.code = 'municipalities' and c.company_id is null
on conflict do nothing;
