"use client";

import { useEffect, useMemo, useState } from "react";
import { Download, Search } from "lucide-react";
import { ComprasNav } from "@/components/compras-nav";
import { api } from "@/lib/api";
import { downloadExcelWorkbook } from "@/lib/reportExports";

type OrderLine = { id: number; item_id?: number | null; item?: { code: string; legacy_code?: string | null; name: string; unit: string } | null; description: string; qty: number; unit: string; unit_cost: number; received_quantity: number; pending_quantity: number; metadata?: { expected_at?: string } };
type PurchaseOrder = { id: number; number: string; status: string; date: string; created_at: string; due_date?: string | null; party?: { id: number; name: string; tax_id?: string }; metadata?: { warehouse_id?: number; warehouse_code?: string; warehouse_name?: string; expected_at?: string }; lines: OrderLine[] };
type ReportRow = { key: string; order: string; sku: string; legacy_code: string; product: string; supplier_id: number; supplier: string; supplier_tax_id: string; warehouse_id: number; warehouse: string; status: string; status_label: string; document_date: string; delivery_date: string; ordered_qty: number; received_qty: number; pending_qty: number; unit_cost: number; ordered_cost: number; received_cost: number; pending_cost: number };

const STATUS_LABELS: Record<string, string> = { draft: "Borrador", confirmed: "Aprobada", approved: "Aprobada", partial: "Recibida parcialmente", completed: "Recibida completamente", closed: "Cerrada", cancelled: "Cancelada" };
const dateOnly = (value?: string | null) => value ? String(value).slice(0, 10) : "";
const money = (value: number) => new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 }).format(value || 0);

export default function PurchaseOrderReportPage() {
  const [orders, setOrders] = useState<PurchaseOrder[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [sku, setSku] = useState("");
  const [supplierId, setSupplierId] = useState("");
  const [warehouseId, setWarehouseId] = useState("");
  const [status, setStatus] = useState("");
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");

  useEffect(() => { api<PurchaseOrder[]>("/api/v1/purchases/orders?all=true").then(setOrders).catch((err) => setError(err instanceof Error ? err.message : "No fue posible cargar el reporte de órdenes" )).finally(() => setLoading(false)); }, []);

  const rows = useMemo<ReportRow[]>(() => orders.flatMap((order) => order.lines.map((line, index) => {
    const orderedQty = Number(line.qty || 0); const receivedQty = Number(line.received_quantity || 0); const pendingQty = Number(line.pending_quantity ?? Math.max(0, orderedQty - receivedQty)); const unitCost = Number(line.unit_cost || 0);
    return { key: `${order.id}-${line.id || index}`, order: order.number, sku: line.item?.code || String(line.item_id || "--"), legacy_code: line.item?.legacy_code || "", product: line.item?.name || line.description, supplier_id: Number(order.party?.id || 0), supplier: order.party?.name || "Sin proveedor", supplier_tax_id: order.party?.tax_id || "", warehouse_id: Number(order.metadata?.warehouse_id || 0), warehouse: [order.metadata?.warehouse_code, order.metadata?.warehouse_name].filter(Boolean).join(" - ") || "Sin bodega", status: order.status, status_label: STATUS_LABELS[order.status] || order.status, document_date: dateOnly(order.date || order.created_at), delivery_date: dateOnly(line.metadata?.expected_at || order.metadata?.expected_at || order.due_date), ordered_qty: orderedQty, received_qty: receivedQty, pending_qty: pendingQty, unit_cost: unitCost, ordered_cost: orderedQty * unitCost, received_cost: receivedQty * unitCost, pending_cost: pendingQty * unitCost };
  })), [orders]);

  const suppliers = useMemo(() => [...new Map(rows.filter((row) => row.supplier_id).map((row) => [row.supplier_id, row.supplier])).entries()].sort((a, b) => a[1].localeCompare(b[1], "es")), [rows]);
  const warehouses = useMemo(() => [...new Map(rows.filter((row) => row.warehouse_id).map((row) => [row.warehouse_id, row.warehouse])).entries()].sort((a, b) => a[1].localeCompare(b[1], "es")), [rows]);
  const statuses = useMemo(() => [...new Set(rows.map((row) => row.status))].sort(), [rows]);
  const visibleRows = useMemo(() => { const needle = sku.trim().toLowerCase(); return rows.filter((row) => (!needle || row.sku.toLowerCase().includes(needle) || row.legacy_code.toLowerCase().includes(needle) || row.product.toLowerCase().includes(needle)) && (!supplierId || row.supplier_id === Number(supplierId)) && (!warehouseId || row.warehouse_id === Number(warehouseId)) && (!status || row.status === status) && (!fromDate || row.document_date >= fromDate) && (!toDate || row.document_date <= toDate)); }, [fromDate, rows, sku, status, supplierId, toDate, warehouseId]);
  const totals = useMemo(() => visibleRows.reduce((sum, row) => ({ ordered: sum.ordered + row.ordered_qty, received: sum.received + row.received_qty, pending: sum.pending + row.pending_qty, orderedCost: sum.orderedCost + row.ordered_cost, receivedCost: sum.receivedCost + row.received_cost, pendingCost: sum.pendingCost + row.pending_cost }), { ordered: 0, received: 0, pending: 0, orderedCost: 0, receivedCost: 0, pendingCost: 0 }), [visibleRows]);

  function exportExcel() { downloadExcelWorkbook("reporte-ordenes-compra.xls", [{ name: "Posiciones OC", columns: [{ key: "pedido", label: "Pedido" }, { key: "sku", label: "SKU" }, { key: "producto", label: "Producto", width: 220 }, { key: "proveedor", label: "Proveedor", width: 180 }, { key: "nit", label: "NIT" }, { key: "bodega", label: "Bodega", width: 180 }, { key: "fecha_documento", label: "Fecha documento" }, { key: "fecha_entrega", label: "Fecha entrega" }, { key: "estado", label: "Estado" }, { key: "cantidad_pedida", label: "Cantidad pedida" }, { key: "cantidad_recibida", label: "Cantidad recibida" }, { key: "cantidad_pendiente", label: "Cantidad pendiente" }, { key: "costo_unitario", label: "Costo unitario" }, { key: "costo_pedido", label: "Costo pedido" }, { key: "costo_recibido", label: "Costo recibido" }, { key: "costo_pendiente", label: "Costo pendiente" }], rows: visibleRows.map((row) => ({ pedido: row.order, sku: row.sku, producto: row.product, proveedor: row.supplier, nit: row.supplier_tax_id, bodega: row.warehouse, fecha_documento: row.document_date, fecha_entrega: row.delivery_date, estado: row.status_label, cantidad_pedida: row.ordered_qty, cantidad_recibida: row.received_qty, cantidad_pendiente: row.pending_qty, costo_unitario: row.unit_cost, costo_pedido: row.ordered_cost, costo_recibido: row.received_cost, costo_pendiente: row.pending_cost })) }]); }

  return <div className="space-y-5"><header className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-medium text-apex">Compras - Reportes</p><h1 className="text-3xl font-semibold">Posiciones de órdenes de compra</h1><p className="mt-1 text-sm text-neutral-600">Compara cantidades y costos pedidos, recibidos y pendientes por posición.</p></div><button className="inline-flex h-10 items-center gap-2 rounded-md border border-line bg-white px-4 text-sm disabled:opacity-50" disabled={!visibleRows.length} onClick={exportExcel} type="button"><Download size={16} /> Excel</button></header><ComprasNav />{error ? <p className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p> : null}
    <section className="rounded-md border border-line bg-white p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-6"><label className="text-sm">SKU o producto<div className="relative mt-1"><Search className="absolute left-3 top-3 text-neutral-400" size={16} /><input className="h-10 w-full rounded-md border border-line pl-10 pr-3" placeholder="Filtrar SKU" value={sku} onChange={(event) => setSku(event.target.value)} /></div></label><label className="text-sm">Proveedor<select className="mt-1 h-10 w-full rounded-md border border-line px-2" value={supplierId} onChange={(event) => setSupplierId(event.target.value)}><option value="">Todos</option>{suppliers.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label className="text-sm">Bodega<select className="mt-1 h-10 w-full rounded-md border border-line px-2" value={warehouseId} onChange={(event) => setWarehouseId(event.target.value)}><option value="">Todas</option>{warehouses.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label className="text-sm">Estado<select className="mt-1 h-10 w-full rounded-md border border-line px-2" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Todos</option>{statuses.map((value) => <option key={value} value={value}>{STATUS_LABELS[value] || value}</option>)}</select></label><label className="text-sm">Fecha desde<input className="mt-1 h-10 w-full rounded-md border border-line px-2" type="date" value={fromDate} onChange={(event) => setFromDate(event.target.value)} /></label><label className="text-sm">Fecha hasta<input className="mt-1 h-10 w-full rounded-md border border-line px-2" type="date" value={toDate} onChange={(event) => setToDate(event.target.value)} /></label></div></section>
    <section className="grid gap-3 md:grid-cols-3 xl:grid-cols-6">{[["Cantidad pedida", totals.ordered], ["Cantidad recibida", totals.received], ["Cantidad pendiente", totals.pending], ["Costo pedido", money(totals.orderedCost)], ["Costo recibido", money(totals.receivedCost)], ["Costo pendiente", money(totals.pendingCost)]].map(([label, value]) => <div className="rounded-md border border-line bg-white p-3" key={String(label)}><span className="text-xs text-neutral-500">{label}</span><strong className="mt-1 block text-lg">{typeof value === "number" ? value.toLocaleString("es-CO") : value}</strong></div>)}</section>
    <section className="overflow-x-auto rounded-md border border-line bg-white"><table className="w-full min-w-[1700px] text-sm"><thead><tr className="border-b border-line bg-paper text-left">{["Pedido", "SKU", "Producto", "Proveedor", "Bodega", "Fecha documento", "Fecha entrega", "Estado", "Cant. pedida", "Cant. recibida", "Cant. pendiente", "Costo unitario", "Costo pedido", "Costo recibido", "Costo pendiente"].map((label) => <th className="px-3 py-2" key={label}>{label}</th>)}</tr></thead><tbody>{visibleRows.map((row) => <tr className="border-b border-line/70" key={row.key}><td className="px-3 py-2 font-mono font-medium">{row.order}</td><td className="px-3 py-2 font-mono">{row.sku}</td><td className="px-3 py-2">{row.product}</td><td className="px-3 py-2">{row.supplier}</td><td className="px-3 py-2">{row.warehouse}</td><td className="px-3 py-2">{row.document_date || "--"}</td><td className="px-3 py-2">{row.delivery_date || "--"}</td><td className="px-3 py-2">{row.status_label}</td><td className="px-3 py-2 text-right">{row.ordered_qty.toLocaleString("es-CO")}</td><td className="px-3 py-2 text-right">{row.received_qty.toLocaleString("es-CO")}</td><td className="px-3 py-2 text-right">{row.pending_qty.toLocaleString("es-CO")}</td><td className="px-3 py-2 text-right">{money(row.unit_cost)}</td><td className="px-3 py-2 text-right">{money(row.ordered_cost)}</td><td className="px-3 py-2 text-right">{money(row.received_cost)}</td><td className="px-3 py-2 text-right">{money(row.pending_cost)}</td></tr>)}{!loading && !visibleRows.length ? <tr><td className="px-4 py-8 text-center text-neutral-500" colSpan={15}>No hay posiciones que coincidan con los filtros.</td></tr> : null}{loading ? <tr><td className="px-4 py-8 text-center text-neutral-500" colSpan={15}>Cargando órdenes...</td></tr> : null}</tbody></table></section>
  </div>;
}
